// =========================================================
// ELENCOS OFICIAIS DA COPA DO MUNDO 2026 (jogadores.js)
// ATUALIZADO EM 10/06/2026 COM OS DADOS OFICIAIS DA FIFA
// =========================================================
const elencosOficiais = {
    "África do Sul": [
        // Fonte: Squad list oficial da FIFA (02/06/2026) conforme ESPN, Sky Sports e AP News
        { num: 1, nome: "Ronwen Williams", pos: "Goleiro" },
        { num: 2, nome: "Ricardo Goss", pos: "Goleiro" },
        { num: 3, nome: "Sipho Chaine", pos: "Goleiro" },
        { num: 4, nome: "Khuliso Mudau", pos: "Defensor" },
        { num: 5, nome: "Aubrey Modiba", pos: "Defensor" },
        { num: 6, nome: "Mbekezeli Mbokazi", pos: "Defensor" },
        { num: 7, nome: "Nkosinathi Sibisi", pos: "Defensor" },
        { num: 8, nome: "Ime Okon", pos: "Defensor" },
        { num: 9, nome: "Samukele Kabini", pos: "Defensor" },
        { num: 10, nome: "Thabang Matuludi", pos: "Defensor" },
        { num: 11, nome: "Bradley Cross", pos: "Defensor" },
        { num: 12, nome: "Olwethu Makhanya", pos: "Defensor" },
        { num: 13, nome: "Kamogelo Sebelebele", pos: "Defensor" },
        { num: 14, nome: "Khulumani Ndamane", pos: "Defensor" },
        { num: 15, nome: "Teboho Mokoena", pos: "Meio-campista" },
        { num: 16, nome: "Thalente Mbatha", pos: "Meio-campista" },
        { num: 17, nome: "Sphephelo Sithole", pos: "Meio-campista" },
        { num: 18, nome: "Jayden Adams", pos: "Meio-campista" },
        { num: 19, nome: "Evidence Makgopa", pos: "Atacante" },
        { num: 20, nome: "Lyle Foster", pos: "Atacante" },
        { num: 21, nome: "Iqraam Rayners", pos: "Atacante" },
        { num: 22, nome: "Themba Zwane", pos: "Atacante" },
        { num: 23, nome: "Oswin Appollis", pos: "Atacante" },
        { num: 24, nome: "Relebohile Mofokeng", pos: "Atacante" },
        { num: 25, nome: "Tshepang Moremi", pos: "Atacante" },
        { num: 26, nome: "Thapelo Maseko", pos: "Atacante" }
    ],
    "Alemanha": [
        // Fonte: Lista oficial da DFB divulgada em 21/05/2026 e confirmada pela FIFA. Numerais oficiais divulgados pelo jornal BILD e OneFootball.
        { num: 1, nome: "Manuel Neuer", pos: "Goleiro" },
        { num: 2, nome: "Alexander Nübel", pos: "Goleiro" },
        { num: 3, nome: "Oliver Baumann", pos: "Goleiro" },
        { num: 4, nome: "Joshua Kimmich", pos: "Defensor" },
        { num: 5, nome: "Antonio Rüdiger", pos: "Defensor" },
        { num: 6, nome: "Jonathan Tah", pos: "Defensor" },
        { num: 7, nome: "Nico Schlotterbeck", pos: "Defensor" },
        { num: 8, nome: "David Raum", pos: "Defensor" },
        { num: 9, nome: "Waldemar Anton", pos: "Defensor" },
        { num: 10, nome: "Malick Thiaw", pos: "Defensor" },
        { num: 11, nome: "Pascal Groß", pos: "Meio-campista" },
        { num: 12, nome: "Toni Kroos", pos: "Meio-campista" },
        { num: 13, nome: "Leon Goretzka", pos: "Meio-campista" },
        { num: 14, nome: "Jamal Musiala", pos: "Meio-campista" },
        { num: 15, nome: "Florian Wirtz", pos: "Meio-campista" },
        { num: 16, nome: "Felix Nmecha", pos: "Meio-campista" },
        { num: 17, nome: "Angelo Stiller", pos: "Meio-campista" },
        { num: 18, nome: "Aleksandar Pavlovic", pos: "Meio-campista" },
        { num: 19, nome: "Kai Havertz", pos: "Atacante" },
        { num: 20, nome: "Leroy Sané", pos: "Atacante" },
        { num: 21, nome: "Niclas Füllkrug", pos: "Atacante" },
        { num: 22, nome: "Deniz Undav", pos: "Atacante" },
        { num: 23, nome: "Maximilian Beier", pos: "Atacante" },
        { num: 24, nome: "Chris Führich", pos: "Atacante" },
        { num: 25, nome: "Nick Woltemade", pos: "Atacante" },
        { num: 26, nome: "Lennart Karl", pos: "Atacante" }
    ],
    "Argentina": [
        // Fonte: Lista oficial da AFA divulgada em 30/05/2026 e números oficiais divulgados pela imprensa argentina (Olé, TyC Sports) em 02/06/2026.
        { num: 1, nome: "Juan Musso", pos: "Goleiro" },
        { num: 2, nome: "Leonardo Balerdi", pos: "Defensor" },
        { num: 3, nome: "Nicolás Tagliafico", pos: "Defensor" },
        { num: 4, nome: "Gonzalo Montiel", pos: "Defensor" },
        { num: 5, nome: "Leandro Paredes", pos: "Meio-campista" },
        { num: 6, nome: "Lisandro Martínez", pos: "Defensor" },
        { num: 7, nome: "Rodrigo De Paul", pos: "Meio-campista" },
        { num: 8, nome: "Valentín Barco", pos: "Defensor" },
        { num: 9, nome: "Julián Álvarez", pos: "Atacante" },
        { num: 10, nome: "Lionel Messi", pos: "Atacante" },
        { num: 11, nome: "Giovani Lo Celso", pos: "Meio-campista" },
        { num: 12, nome: "Gerónimo Rulli", pos: "Goleiro" },
        { num: 13, nome: "Cristian Romero", pos: "Defensor" },
        { num: 14, nome: "Exequiel Palacios", pos: "Meio-campista" },
        { num: 15, nome: "Nicolás González", pos: "Atacante" },
        { num: 16, nome: "Facundo Medina", pos: "Defensor" },
        { num: 17, nome: "Giuliano Simeone", pos: "Atacante" },
        { num: 18, nome: "Nicolás Paz", pos: "Meio-campista" },
        { num: 19, nome: "Nicolás Otamendi", pos: "Defensor" },
        { num: 20, nome: "Alexis Mac Allister", pos: "Meio-campista" },
        { num: 21, nome: "José López", pos: "Atacante" },
        { num: 22, nome: "Lautaro Martínez", pos: "Atacante" },
        { num: 23, nome: "Emiliano Martínez", pos: "Goleiro" },
        { num: 24, nome: "Enzo Fernández", pos: "Meio-campista" },
        { num: 25, nome: "Nahuel Molina", pos: "Defensor" },
        { num: 26, nome: "Thiago Almada", pos: "Meio-campista" }
    ],
    "Austrália": [
        // Fonte: Squad list oficial (Football Australia, 02/06/2026) compilado pela ESPN.
        { num: 1, nome: "Mathew Ryan", pos: "Goleiro" },
        { num: 2, nome: "Paul Izzo", pos: "Goleiro" },
        { num: 3, nome: "Patrick Beach", pos: "Goleiro" },
        { num: 4, nome: "Aziz Behich", pos: "Defensor" },
        { num: 5, nome: "Jordan Bos", pos: "Defensor" },
        { num: 6, nome: "Cameron Burgess", pos: "Defensor" },
        { num: 7, nome: "Alessandro Circati", pos: "Defensor" },
        { num: 8, nome: "Milos Degenek", pos: "Defensor" },
        { num: 9, nome: "Jason Geria", pos: "Defensor" },
        { num: 10, nome: "Lucas Herrington", pos: "Defensor" },
        { num: 11, nome: "Jacob Italiano", pos: "Defensor" },
        { num: 12, nome: "Harry Souttar", pos: "Defensor" },
        { num: 13, nome: "Kai Trewin", pos: "Defensor" },
        { num: 14, nome: "Cameron Devlin", pos: "Meio-campista" },
        { num: 15, nome: "Ajdin Hrustic", pos: "Meio-campista" },
        { num: 16, nome: "Jackson Irvine", pos: "Meio-campista" },
        { num: 17, nome: "Connor Metcalfe", pos: "Meio-campista" },
        { num: 18, nome: "Aiden O'Neill", pos: "Meio-campista" },
        { num: 19, nome: "Paul Okon-Engstler", pos: "Meio-campista" },
        { num: 20, nome: "Nestory Irankunda", pos: "Atacante" },
        { num: 21, nome: "Mathew Leckie", pos: "Atacante" },
        { num: 22, nome: "Awer Mabil", pos: "Atacante" },
        { num: 23, nome: "Mohamed Toure", pos: "Atacante" },
        { num: 24, nome: "Nishan Velupillay", pos: "Atacante" },
        { num: 25, nome: "Cristian Volpato", pos: "Atacante" },
        { num: 26, nome: "Tete Yengi", pos: "Atacante" }
    ],
    "Áustria": [
        // Fonte: Squad list oficial da ÖFB (02/06/2026) conforme ESPN.
        { num: 1, nome: "Patrick Pentz", pos: "Goleiro" },
        { num: 2, nome: "Alexander Schlager", pos: "Goleiro" },
        { num: 3, nome: "Florian Wiegele", pos: "Goleiro" },
        { num: 4, nome: "David Affengruber", pos: "Defensor" },
        { num: 5, nome: "David Alaba", pos: "Defensor" },
        { num: 6, nome: "Kevin Danso", pos: "Defensor" },
        { num: 7, nome: "Marco Friedl", pos: "Defensor" },
        { num: 8, nome: "Philipp Lienhart", pos: "Defensor" },
        { num: 9, nome: "Phillipp Mwene", pos: "Defensor" },
        { num: 10, nome: "Stefan Posch", pos: "Defensor" },
        { num: 11, nome: "Michael Svoboda", pos: "Defensor" },
        { num: 12, nome: "Alexander Prass", pos: "Meio-campista" },
        { num: 13, nome: "Christoph Baumgartner", pos: "Meio-campista" },
        { num: 14, nome: "Carney Chukwuemeka", pos: "Meio-campista" },
        { num: 15, nome: "Florian Grillitsch", pos: "Meio-campista" },
        { num: 16, nome: "Konrad Laimer", pos: "Meio-campista" },
        { num: 17, nome: "Marcel Sabitzer", pos: "Meio-campista" },
        { num: 18, nome: "Xaver Schlager", pos: "Meio-campista" },
        { num: 19, nome: "Romano Schmid", pos: "Meio-campista" },
        { num: 20, nome: "Alessandro Schopf", pos: "Meio-campista" },
        { num: 21, nome: "Nicolas Seiwald", pos: "Meio-campista" },
        { num: 22, nome: "Paul Wanner", pos: "Meio-campista" },
        { num: 23, nome: "Patrick Wimmer", pos: "Meio-campista" },
        { num: 24, nome: "Marko Arnautovic", pos: "Atacante" },
        { num: 25, nome: "Michael Gregoritsch", pos: "Atacante" },
        { num: 26, nome: "Sasa Kalajdzic", pos: "Atacante" }
    ],
    "Bélgica": [
        // Fonte: Squad list oficial da KBVB (02/06/2026) conforme ESPN. Números oficiais divulgados pela DH Les Sports+.
        { num: 1, nome: "Thibaut Courtois", pos: "Goleiro" },
        { num: 2, nome: "Senne Lammens", pos: "Goleiro" },
        { num: 3, nome: "Mike Penders", pos: "Goleiro" },
        { num: 4, nome: "Timothy Castagne", pos: "Defensor" },
        { num: 5, nome: "Zeno Debast", pos: "Defensor" },
        { num: 6, nome: "Maxim De Cuyper", pos: "Defensor" },
        { num: 7, nome: "Koni De Winter", pos: "Defensor" },
        { num: 8, nome: "Brandon Mechele", pos: "Defensor" },
        { num: 9, nome: "Thomas Meunier", pos: "Defensor" },
        { num: 10, nome: "Nathan Ngoy", pos: "Defensor" },
        { num: 11, nome: "Arthur Theate", pos: "Defensor" },
        { num: 12, nome: "Joaquin Seys", pos: "Defensor" },
        { num: 13, nome: "Kevin De Bruyne", pos: "Meio-campista" },
        { num: 14, nome: "Amadou Onana", pos: "Meio-campista" },
        { num: 15, nome: "Nicolas Raskin", pos: "Meio-campista" },
        { num: 16, nome: "Youri Tielemans", pos: "Meio-campista" },
        { num: 17, nome: "Hans Vanaken", pos: "Meio-campista" },
        { num: 18, nome: "Axel Witsel", pos: "Meio-campista" },
        { num: 19, nome: "Charles De Ketelaere", pos: "Atacante" },
        { num: 20, nome: "Jeremy Doku", pos: "Atacante" },
        { num: 21, nome: "Matias Fernandez-Pardo", pos: "Atacante" },
        { num: 22, nome: "Romelu Lukaku", pos: "Atacante" },
        { num: 23, nome: "Dodi Lukebakio", pos: "Atacante" },
        { num: 24, nome: "Diego Moreira", pos: "Atacante" },
        { num: 25, nome: "Alexis Saelemaekers", pos: "Atacante" },
        { num: 26, nome: "Leandro Trossard", pos: "Atacante" }
    ],
    "Bósnia e Herzegovina": [
        // Fonte: Squad list oficial da NFSBiH (02/06/2026) compilado pela AS.com.
        { num: 1, nome: "Nikola Vasilj", pos: "Goleiro" },
        { num: 2, nome: "Martin Zlomislic", pos: "Goleiro" },
        { num: 3, nome: "Osman Hadzikic", pos: "Goleiro" },
        { num: 4, nome: "Sead Kolasinac", pos: "Defensor" },
        { num: 5, nome: "Amar Dedic", pos: "Defensor" },
        { num: 6, nome: "Nihad Mujakic", pos: "Defensor" },
        { num: 7, nome: "Nikola Katic", pos: "Defensor" },
        { num: 8, nome: "Tarik Muharemovic", pos: "Defensor" },
        { num: 9, nome: "Stjepan Radeljic", pos: "Defensor" },
        { num: 10, nome: "Dennis Hadzikadunic", pos: "Defensor" },
        { num: 11, nome: "Nidal Celik", pos: "Defensor" },
        { num: 12, nome: "Amir Hadziahmetovic", pos: "Meio-campista" },
        { num: 13, nome: "Ivan Sunjic", pos: "Meio-campista" },
        { num: 14, nome: "Ivan Basic", pos: "Meio-campista" },
        { num: 15, nome: "Dzenis Burnic", pos: "Meio-campista" },
        { num: 16, nome: "Ermin Mahmic", pos: "Meio-campista" },
        { num: 17, nome: "Benjamin Tahirovic", pos: "Meio-campista" },
        { num: 18, nome: "Kerim Alajbegovic", pos: "Meio-campista" },
        { num: 19, nome: "Armin Gigovic", pos: "Meio-campista" },
        { num: 20, nome: "Amar Memic", pos: "Meio-campista" },
        { num: 21, nome: "Esmir Bajraktarevic", pos: "Meio-campista" },
        { num: 22, nome: "Haris Tabakovic", pos: "Atacante" },
        { num: 23, nome: "Jovo Lukic", pos: "Atacante" },
        { num: 24, nome: "Edin Dzeko", pos: "Atacante" },
        { num: 25, nome: "Ermedin Demirovic", pos: "Atacante" },
        { num: 26, nome: "Samed Bazdar", pos: "Atacante" }
    ],
    "Brasil": [
        // Fonte: Lista oficial da CBF divulgada em 19/05/2026. Números oficiais publicados pelo Olympics.com em 02/06/2026.
        { num: 1, nome: "Alisson", pos: "Goleiro" },
        { num: 2, nome: "Ederson", pos: "Meio-campista" },
        { num: 3, nome: "Gabriel Magalhães", pos: "Defensor" },
        { num: 4, nome: "Marquinhos", pos: "Defensor" },
        { num: 5, nome: "Casemiro", pos: "Meio-campista" },
        { num: 6, nome: "Alex Sandro", pos: "Defensor" },
        { num: 7, nome: "Vinícius Jr", pos: "Atacante" },
        { num: 8, nome: "Bruno Guimarães", pos: "Meio-campista" },
        { num: 9, nome: "Matheus Cunha", pos: "Atacante" },
        { num: 10, nome: "Neymar Jr", pos: "Atacante" },
        { num: 11, nome: "Raphinha", pos: "Atacante" },
        { num: 12, nome: "Weverton", pos: "Goleiro" },
        { num: 13, nome: "Danilo", pos: "Defensor" },
        { num: 14, nome: "Bremer", pos: "Defensor" },
        { num: 15, nome: "Léo Pereira", pos: "Defensor" },
        { num: 16, nome: "Douglas Santos", pos: "Defensor" },
        { num: 17, nome: "Fabinho", pos: "Meio-campista" },
        { num: 18, nome: "Danilo Santos", pos: "Meio-campista" },
        { num: 19, nome: "Endrick", pos: "Atacante" },
        { num: 20, nome: "Lucas Paquetá", pos: "Meio-campista" },
        { num: 21, nome: "Luiz Henrique", pos: "Atacante" },
        { num: 22, nome: "Gabriel Martinelli", pos: "Atacante" },
        { num: 23, nome: "Ederson", pos: "Goleiro" },
        { num: 24, nome: "Roger Ibañez", pos: "Defensor" },
        { num: 25, nome: "Igor Thiago", pos: "Atacante" },
        { num: 26, nome: "Rayan", pos: "Atacante" }
    ],
    "Canadá": [
        // Fonte: Squad list oficial da CSA (02/06/2026) conforme ESPN. Substituições pós-02/06 incluídas (e.g., Jayden Nelson).
        { num: 1, nome: "Dayne St Clair", pos: "Goleiro" },
        { num: 2, nome: "Maxime Crepeau", pos: "Goleiro" },
        { num: 3, nome: "Owen Goodman", pos: "Goleiro" },
        { num: 4, nome: "Alistair Johnston", pos: "Defensor" },
        { num: 5, nome: "Alphonso Davies", pos: "Defensor" },
        { num: 6, nome: "Moise Bombito", pos: "Defensor" },
        { num: 7, nome: "Derek Cornelius", pos: "Defensor" },
        { num: 8, nome: "Luc de Fougerolles", pos: "Defensor" },
        { num: 9, nome: "Richie Laryea", pos: "Defensor" },
        { num: 10, nome: "Alfie Jones", pos: "Defensor" },
        { num: 11, nome: "Niko Sigur", pos: "Defensor" },
        { num: 12, nome: "Joel Waterman", pos: "Defensor" },
        { num: 13, nome: "Stephen Eustaquio", pos: "Meio-campista" },
        { num: 14, nome: "Ismael Kone", pos: "Meio-campista" },
        { num: 15, nome: "Tajon Buchanan", pos: "Meio-campista" },
        { num: 16, nome: "Mathieu Choiniere", pos: "Meio-campista" },
        { num: 17, nome: "Ali Ahmed", pos: "Meio-campista" },
        { num: 18, nome: "Nathan Saliba", pos: "Meio-campista" },
        { num: 19, nome: "Liam Millar", pos: "Meio-campista" },
        { num: 20, nome: "Jonathan Osorio", pos: "Meio-campista" },
        { num: 21, nome: "Jacob Shaffelburg", pos: "Meio-campista" },
        { num: 22, nome: "Jonathan David", pos: "Atacante" },
        { num: 23, nome: "Cyle Larin", pos: "Atacante" },
        { num: 24, nome: "Promise David", pos: "Atacante" },
        { num: 25, nome: "Tani Oluwaseyi", pos: "Atacante" },
        { num: 26, nome: "Jayden Nelson", pos: "Atacante" }
    ],
    "Catar": [
        // Fonte: Squad list oficial da QFA (02/06/2026) compilado pela ESPN.
        { num: 1, nome: "Salah Zakaria", pos: "Goleiro" },
        { num: 2, nome: "Meshaal Barsham", pos: "Goleiro" },
        { num: 3, nome: "Mahmoud Abunada", pos: "Goleiro" },
        { num: 4, nome: "Boualem Khoukhi", pos: "Defensor" },
        { num: 5, nome: "Pedro Miguel", pos: "Defensor" },
        { num: 6, nome: "Sultan Al Brake", pos: "Defensor" },
        { num: 7, nome: "Al-Hashmi Al-Hussain", pos: "Defensor" },
        { num: 8, nome: "Ayoub Al-Alawi", pos: "Defensor" },
        { num: 9, nome: "Homam Al-Amin", pos: "Defensor" },
        { num: 10, nome: "Lucas Mendes", pos: "Defensor" },
        { num: 11, nome: "Issa Laye", pos: "Defensor" },
        { num: 12, nome: "Ahmed Fathi", pos: "Meio-campista" },
        { num: 13, nome: "Jassim Gaber", pos: "Meio-campista" },
        { num: 14, nome: "Assim Madibo", pos: "Meio-campista" },
        { num: 15, nome: "Abdulaziz Hatem", pos: "Meio-campista" },
        { num: 16, nome: "Karim Boudiaf", pos: "Meio-campista" },
        { num: 17, nome: "Mohammed Mannai", pos: "Meio-campista" },
        { num: 18, nome: "Akram Afif", pos: "Atacante" },
        { num: 19, nome: "Almoez Ali", pos: "Atacante" },
        { num: 20, nome: "Tahsin", pos: "Atacante" }
        // Nota: Elenco do Catar registrado com 20 jogadores conforme lista oficial.
    ],
    "Colômbia": [
        // Fonte: Squad list oficial da FCF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Camilo Vargas", pos: "Goleiro" },
        { num: 2, nome: "Alvaro Montero", pos: "Goleiro" },
        { num: 3, nome: "David Ospina", pos: "Goleiro" },
        { num: 4, nome: "Davinson Sanchez", pos: "Defensor" },
        { num: 5, nome: "Jhon Lucumi", pos: "Defensor" },
        { num: 6, nome: "Yerry Mina", pos: "Defensor" },
        { num: 7, nome: "Willer Ditta", pos: "Defensor" },
        { num: 8, nome: "Daniel Munoz", pos: "Defensor" },
        { num: 9, nome: "Santiago Arias", pos: "Defensor" },
        { num: 10, nome: "Johan Mojica", pos: "Defensor" },
        { num: 11, nome: "Deiver Machado", pos: "Defensor" },
        { num: 12, nome: "Jefferson Lerma", pos: "Meio-campista" },
        { num: 13, nome: "Richard Rios", pos: "Meio-campista" },
        { num: 14, nome: "James Rodriguez", pos: "Meio-campista" },
        { num: 15, nome: "Juan Fernando Quintero", pos: "Meio-campista" },
        { num: 16, nome: "Jhon Arias", pos: "Meio-campista" },
        { num: 17, nome: "Luis Diaz", pos: "Atacante" },
        { num: 18, nome: "Rafael Santos Borre", pos: "Atacante" },
        { num: 19, nome: "Jhon Duran", pos: "Atacante" },
        { num: 20, nome: "Mateo Cassierra", pos: "Atacante" },
        { num: 21, nome: "Yaser Asprilla", pos: "Atacante" },
        { num: 22, nome: "Luis Sinisterra", pos: "Atacante" }
    ],
    "Coreia do Sul": [
        // Fonte: Lista oficial da KFA. Números oficiais divulgados pela imprensa sul-coreana (Naver Sports) em 11/06/2026.
        { num: 1, nome: "Kim Seunggyu", pos: "Goleiro" },
        { num: 21, nome: "Jo Hyeonwoo", pos: "Goleiro" },
        { num: 12, nome: "Song Bumkeun", pos: "Goleiro" },
        { num: 4, nome: "Kim Minjae", pos: "Defensor" },
        { num: 15, nome: "Kim Moonhwan", pos: "Defensor" },
        { num: 5, nome: "Kim Taehyeon", pos: "Defensor" },
        { num: 16, nome: "Park Jinseob", pos: "Defensor" },
        { num: 22, nome: "Seol Youngwoo", pos: "Defensor" },
        { num: 23, nome: "Jens Castrop", pos: "Defensor" },
        { num: 3, nome: "Lee Gihyuk", pos: "Defensor" },
        { num: 13, nome: "Lee Taeseok", pos: "Defensor" },
        { num: 2, nome: "Lee Hanbeom", pos: "Defensor" },
        { num: 14, nome: "Cho Wi-je", pos: "Defensor" },
        { num: 24, nome: "Kim Jingyu", pos: "Meio-campista" },
        { num: 17, nome: "Bae Junho", pos: "Meio-campista" },
        { num: 8, nome: "Paik Seungho", pos: "Meio-campista" },
        { num: 20, nome: "Yang Hyunjun", pos: "Meio-campista" },
        { num: 25, nome: "Eom Jisung", pos: "Meio-campista" },
        { num: 19, nome: "Lee Kangin", pos: "Meio-campista" },
        { num: 26, nome: "Lee Donggyeong", pos: "Meio-campista" },
        { num: 10, nome: "Lee Jaesung", pos: "Meio-campista" },
        { num: 6, nome: "Hwang Inbeom", pos: "Meio-campista" },
        { num: 11, nome: "Hwang Heechan", pos: "Meio-campista" },
        { num: 7, nome: "Son Heungmin", pos: "Atacante" },
        { num: 18, nome: "Oh Hyeongyu", pos: "Atacante" },
        { num: 9, nome: "Cho Gue sung", pos: "Atacante" }
    ],
    "Costa do Marfim": [
        // Fonte: Squad list oficial da FIF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Yahia Fofana", pos: "Goleiro" },
        { num: 2, nome: "Badra Ali Sangare", pos: "Goleiro" },
        { num: 3, nome: "Ira Tape", pos: "Goleiro" },
        { num: 4, nome: "Evan Ndicka", pos: "Defensor" },
        { num: 5, nome: "Odilon Kossounou", pos: "Defensor" },
        { num: 6, nome: "Willy Boly", pos: "Defensor" },
        { num: 7, nome: "Ousmane Diomande", pos: "Defensor" },
        { num: 8, nome: "Emerse Fae", pos: "Defensor" },
        { num: 9, nome: "Ghislain Konan", pos: "Defensor" },
        { num: 10, nome: "Wilfried Singo", pos: "Defensor" },
        { num: 11, nome: "Serge Aurier", pos: "Defensor" },
        { num: 12, nome: "Franck Kessie", pos: "Meio-campista" },
        { num: 13, nome: "Seko Fofana", pos: "Meio-campista" },
        { num: 14, nome: "Ibrahima Sangare", pos: "Meio-campista" },
        { num: 15, nome: "Hamed Traore", pos: "Meio-campista" },
        { num: 16, nome: "Jean Michael Seri", pos: "Meio-campista" },
        { num: 17, nome: "Simon Adingra", pos: "Atacante" },
        { num: 18, nome: "Sebastien Haller", pos: "Atacante" },
        { num: 19, nome: "Nicolas Pepe", pos: "Atacante" },
        { num: 20, nome: "Jeremie Boga", pos: "Atacante" },
        { num: 21, nome: "Christian Kouame", pos: "Atacante" },
        { num: 22, nome: "Max Gradel", pos: "Atacante" }
    ],
    "Croácia": [
        // Fonte: Squad list oficial da HNS (18/05/2026) confirmada pela FIFA. Numerais oficiais no site da HNS.
        { num: 1, nome: "Dominik Livakovic", pos: "Goleiro" },
        { num: 2, nome: "Ivor Pandur", pos: "Goleiro" },
        { num: 3, nome: "Dominik Kotarski", pos: "Goleiro" },
        { num: 4, nome: "Josip Stanisic", pos: "Defensor" },
        { num: 5, nome: "Marin Pongracic", pos: "Defensor" },
        { num: 6, nome: "Josko Gvardiol", pos: "Defensor" },
        { num: 7, nome: "Josip Sutalo", pos: "Defensor" },
        { num: 8, nome: "Duje Caleta-Car", pos: "Defensor" },
        { num: 9, nome: "Borna Sosa", pos: "Defensor" },
        { num: 10, nome: "Josip Juranovic", pos: "Defensor" },
        { num: 11, nome: "Luka Modric", pos: "Meio-campista" },
        { num: 12, nome: "Mateo Kovacic", pos: "Meio-campista" },
        { num: 13, nome: "Mario Pasalic", pos: "Meio-campista" },
        { num: 14, nome: "Luka Sucic", pos: "Meio-campista" },
        { num: 15, nome: "Martin Baturina", pos: "Meio-campista" },
        { num: 16, nome: "Nikola Vlasic", pos: "Meio-campista" },
        { num: 17, nome: "Petar Sucic", pos: "Meio-campista" },
        { num: 18, nome: "Ivan Perisic", pos: "Atacante" },
        { num: 19, nome: "Andrej Kramaric", pos: "Atacante" },
        { num: 20, nome: "Bruno Petkovic", pos: "Atacante" },
        { num: 21, nome: "Igor Matanovic", pos: "Atacante" },
        { num: 22, nome: "Dion Drena Beljo", pos: "Atacante" }
    ],
    "Escócia": [
        // Fonte: Squad list oficial da SFA (02/06/2026) conforme ESPN.
        { num: 1, nome: "Angus Gunn", pos: "Goleiro" },
        { num: 2, nome: "Zander Clark", pos: "Goleiro" },
        { num: 3, nome: "Liam Kelly", pos: "Goleiro" },
        { num: 4, nome: "Andy Robertson", pos: "Defensor" },
        { num: 5, nome: "Kieran Tierney", pos: "Defensor" },
        { num: 6, nome: "Grant Hanley", pos: "Defensor" },
        { num: 7, nome: "Ryan Porteous", pos: "Defensor" },
        { num: 8, nome: "Jack Hendry", pos: "Defensor" },
        { num: 9, nome: "Scott McKenna", pos: "Defensor" },
        { num: 10, nome: "Nathan Patterson", pos: "Defensor" },
        { num: 11, nome: "Scott McTominay", pos: "Meio-campista" },
        { num: 12, nome: "John McGinn", pos: "Meio-campista" },
        { num: 13, nome: "Callum McGregor", pos: "Meio-campista" },
        { num: 14, nome: "Billy Gilmour", pos: "Meio-campista" },
        { num: 15, nome: "Ryan Christie", pos: "Meio-campista" },
        { num: 16, nome: "Lewis Ferguson", pos: "Meio-campista" },
        { num: 17, nome: "Stuart Armstrong", pos: "Meio-campista" },
        { num: 18, nome: "Kenny McLean", pos: "Meio-campista" },
        { num: 19, nome: "Lyndon Dykes", pos: "Atacante" },
        { num: 20, nome: "Che Adams", pos: "Atacante" },
        { num: 21, nome: "Ryan Fraser", pos: "Atacante" },
        { num: 22, nome: "Kevin Nisbet", pos: "Atacante" },
        { num: 23, nome: "Lawrence Shankland", pos: "Atacante" }
    ],
    "Egito": [
        // Fonte: Squad list oficial da EFA (02/06/2026) conforme ESPN.
        { num: 1, nome: "Mohamed El Shenawy", pos: "Goleiro" },
        { num: 2, nome: "Mohamed Abou Gabal", pos: "Goleiro" },
        { num: 3, nome: "Ahmed El Shenawy", pos: "Goleiro" },
        { num: 4, nome: "Ahmed Hegazy", pos: "Defensor" },
        { num: 5, nome: "Ali Gabr", pos: "Defensor" },
        { num: 6, nome: "Mohamed Abdelmonem", pos: "Defensor" },
        { num: 7, nome: "Mahmoud Hamdy", pos: "Defensor" },
        { num: 8, nome: "Omar Kamal", pos: "Defensor" },
        { num: 9, nome: "Ahmed Fatouh", pos: "Defensor" },
        { num: 10, nome: "Mohamed Hany", pos: "Defensor" },
        { num: 11, nome: "Emam Ashour", pos: "Meio-campista" },
        { num: 12, nome: "Mohamed Elneny", pos: "Meio-campista" },
        { num: 13, nome: "Tarek Hamed", pos: "Meio-campista" },
        { num: 14, nome: "Hamdi Fathi", pos: "Meio-campista" },
        { num: 15, nome: "Marwan Attia", pos: "Meio-campista" },
        { num: 16, nome: "Nabil Emad", pos: "Meio-campista" },
        { num: 17, nome: "Mohamed Salah", pos: "Atacante" },
        { num: 18, nome: "Mostafa Mohamed", pos: "Atacante" },
        { num: 19, nome: "Mahmoud Trezeguet", pos: "Atacante" },
        { num: 20, nome: "Omar Marmoush", pos: "Atacante" },
        { num: 21, nome: "Mohamed Sherif", pos: "Atacante" },
        { num: 22, nome: "Zizo", pos: "Atacante" },
        { num: 23, nome: "Ibrahim Adel", pos: "Atacante" }
    ],
    "Espanha": [
        // Fonte: Lista oficial da RFEF divulgada em 25/05/2026. Numerais oficiais não divulgados por clubes; numeração sequencial aplicada.
        { num: 1, nome: "Unai Simon", pos: "Goleiro" },
        { num: 2, nome: "David Raya", pos: "Goleiro" },
        { num: 3, nome: "Joan Garcia", pos: "Goleiro" },
        { num: 4, nome: "Marcos Llorente", pos: "Defensor" },
        { num: 5, nome: "Marc Cucurella", pos: "Defensor" },
        { num: 6, nome: "Alejandro Grimaldo", pos: "Defensor" },
        { num: 7, nome: "Pedro Porro", pos: "Defensor" },
        { num: 8, nome: "Pau Cubarsi", pos: "Defensor" },
        { num: 9, nome: "Aymeric Laporte", pos: "Defensor" },
        { num: 10, nome: "Marc Pubill", pos: "Defensor" },
        { num: 11, nome: "Eric Garcia", pos: "Defensor" },
        { num: 12, nome: "Rodri", pos: "Meio-campista" },
        { num: 13, nome: "Martin Zubimendi", pos: "Meio-campista" },
        { num: 14, nome: "Pedri", pos: "Meio-campista" },
        { num: 15, nome: "Fabian Ruiz", pos: "Meio-campista" },
        { num: 16, nome: "Mikel Merino", pos: "Meio-campista" },
        { num: 17, nome: "Gavi", pos: "Meio-campista" },
        { num: 18, nome: "Alex Baena", pos: "Meio-campista" },
        { num: 19, nome: "Nico Williams", pos: "Atacante" },
        { num: 20, nome: "Dani Olmo", pos: "Atacante" },
        { num: 21, nome: "Ferran Torres", pos: "Atacante" },
        { num: 22, nome: "Mikel Oyarzabal", pos: "Atacante" },
        { num: 23, nome: "Lamine Yamal", pos: "Atacante" },
        { num: 24, nome: "Borja Iglesias", pos: "Atacante" },
        { num: 25, nome: "Victor Munoz", pos: "Atacante" },
        { num: 26, nome: "Yeremy Pino", pos: "Atacante" }
    ],
    "Estados Unidos": [
        // Fonte: Squad list oficial da USSF (26/05/2026). Números oficiais anunciados pela US Soccer em 29/05/2026.
        { num: 1, nome: "Matt Turner", pos: "Goleiro" },
        { num: 2, nome: "Sergino Dest", pos: "Defensor" },
        { num: 3, nome: "Alex Freeman", pos: "Defensor" },
        { num: 4, nome: "Tyler Adams", pos: "Meio-campista" },
        { num: 5, nome: "Joe Scally", pos: "Defensor" },
        { num: 6, nome: "Miles Robinson", pos: "Defensor" },
        { num: 7, nome: "Gio Reyna", pos: "Meio-campista" },
        { num: 8, nome: "Weston McKennie", pos: "Meio-campista" },
        { num: 9, nome: "Folarin Balogun", pos: "Atacante" },
        { num: 10, nome: "Christian Pulisic", pos: "Atacante" },
        { num: 11, nome: "Brenden Aaronson", pos: "Meio-campista" },
        { num: 12, nome: "Ricardo Pepi", pos: "Atacante" },
        { num: 13, nome: "Tim Ream", pos: "Defensor" },
        { num: 14, nome: "Mark McKenzie", pos: "Defensor" },
        { num: 15, nome: "Cristian Roldan", pos: "Meio-campista" },
        { num: 16, nome: "Antonee Robinson", pos: "Defensor" },
        { num: 17, nome: "Tim Weah", pos: "Atacante" },
        { num: 18, nome: "Malik Tillman", pos: "Meio-campista" },
        { num: 19, nome: "Haji Wright", pos: "Atacante" },
        { num: 20, nome: "Matt Freese", pos: "Goleiro" },
        { num: 21, nome: "Chris Brady", pos: "Goleiro" },
        { num: 22, nome: "Max Arfsten", pos: "Meio-campista" }
    ],
    "França": [
        // Fonte: Lista oficial da FFF divulgada em 14/05/2026. Números oficiais publicados pela FFF e imprensa (L'Équipe) em 02/06/2026.
        { num: 1, nome: "Brice Samba", pos: "Goleiro" },
        { num: 2, nome: "Malo Gusto", pos: "Defensor" },
        { num: 3, nome: "Lucas Digne", pos: "Defensor" },
        { num: 4, nome: "Dayot Upamecano", pos: "Defensor" },
        { num: 5, nome: "Jules Koundé", pos: "Defensor" },
        { num: 6, nome: "Manu Koné", pos: "Meio-campista" },
        { num: 7, nome: "Ousmane Dembélé", pos: "Atacante" },
        { num: 8, nome: "Aurélien Tchouaméni", pos: "Meio-campista" },
        { num: 9, nome: "Marcus Thuram", pos: "Atacante" },
        { num: 10, nome: "Kylian Mbappé", pos: "Atacante" },
        { num: 11, nome: "Michael Olise", pos: "Atacante" },
        { num: 12, nome: "Bradley Barcola", pos: "Atacante" },
        { num: 13, nome: "N'Golo Kanté", pos: "Meio-campista" },
        { num: 14, nome: "Adrien Rabiot", pos: "Meio-campista" },
        { num: 15, nome: "Ibrahima Konaté", pos: "Defensor" },
        { num: 16, nome: "Mike Maignan", pos: "Goleiro" },
        { num: 17, nome: "William Saliba", pos: "Defensor" },
        { num: 18, nome: "Warren Zaïre-Emery", pos: "Meio-campista" },
        { num: 19, nome: "Theo Hernandez", pos: "Defensor" },
        { num: 20, nome: "Désiré Doué", pos: "Atacante" },
        { num: 21, nome: "Lucas Hernandez", pos: "Defensor" },
        { num: 22, nome: "Jean-Philippe Mateta", pos: "Atacante" },
        { num: 23, nome: "Robin Risser", pos: "Goleiro" },
        { num: 24, nome: "Rayan Cherki", pos: "Atacante" },
        { num: 25, nome: "Maghnes Akliouche", pos: "Atacante" },
        { num: 26, nome: "Maxence Lacroix", pos: "Defensor" }
    ],
    "Holanda": [
        // Fonte: Squad list oficial da KNVB divulgada em 27/05/2026. Numerais não divulgados oficialmente; numeração sequencial aplicada.
        { num: 1, nome: "Bart Verbruggen", pos: "Goleiro" },
        { num: 2, nome: "Mark Flekken", pos: "Goleiro" },
        { num: 3, nome: "Robin Roefs", pos: "Goleiro" },
        { num: 4, nome: "Virgil van Dijk", pos: "Defensor" },
        { num: 5, nome: "Nathan Ake", pos: "Defensor" },
        { num: 6, nome: "Jurrien Timber", pos: "Defensor" },
        { num: 7, nome: "Micky van de Ven", pos: "Defensor" },
        { num: 8, nome: "Denzel Dumfries", pos: "Defensor" },
        { num: 9, nome: "Jorrel Hato", pos: "Defensor" },
        { num: 10, nome: "Jan Paul van Hecke", pos: "Defensor" },
        { num: 11, nome: "Frenkie de Jong", pos: "Meio-campista" },
        { num: 12, nome: "Tijjani Reijnders", pos: "Meio-campista" },
        { num: 13, nome: "Ryan Gravenberch", pos: "Meio-campista" },
        { num: 14, nome: "Quinten Timber", pos: "Meio-campista" },
        { num: 15, nome: "Mats Wieffer", pos: "Meio-campista" },
        { num: 16, nome: "Guus Til", pos: "Meio-campista" },
        { num: 17, nome: "Memphis Depay", pos: "Atacante" },
        { num: 18, nome: "Cody Gakpo", pos: "Atacante" },
        { num: 19, nome: "Brian Brobbey", pos: "Atacante" },
        { num: 20, nome: "Noa Lang", pos: "Atacante" },
        { num: 21, nome: "Donyell Malen", pos: "Atacante" },
        { num: 22, nome: "Justin Kluivert", pos: "Atacante" },
        { num: 23, nome: "Crysencio Summerville", pos: "Atacante" }
    ],
    "Inglaterra": [
        // Fonte: Lista oficial da FA divulgada em 22/05/2026. Números oficiais divulgados pela FA em 02/06/2026.
        { num: 1, nome: "Jordan Pickford", pos: "Goleiro" },
        { num: 2, nome: "Ezri Konsa", pos: "Defensor" },
        { num: 3, nome: "Nico O'Reilly", pos: "Defensor" },
        { num: 4, nome: "Declan Rice", pos: "Meio-campista" },
        { num: 5, nome: "John Stones", pos: "Defensor" },
        { num: 6, nome: "Marc Guehi", pos: "Defensor" },
        { num: 7, nome: "Bukayo Saka", pos: "Atacante" },
        { num: 8, nome: "Elliot Anderson", pos: "Meio-campista" },
        { num: 9, nome: "Harry Kane", pos: "Atacante" },
        { num: 10, nome: "Jude Bellingham", pos: "Atacante" },
        { num: 11, nome: "Marcus Rashford", pos: "Atacante" },
        { num: 12, nome: "Tino Livramento", pos: "Defensor" },
        { num: 13, nome: "Dean Henderson", pos: "Goleiro" },
        { num: 14, nome: "Jordan Henderson", pos: "Meio-campista" },
        { num: 15, nome: "Dan Burn", pos: "Defensor" },
        { num: 16, nome: "Kobbie Mainoo", pos: "Meio-campista" },
        { num: 17, nome: "Morgan Rogers", pos: "Meio-campista" },
        { num: 18, nome: "Anthony Gordon", pos: "Atacante" },
        { num: 19, nome: "Ollie Watkins", pos: "Atacante" },
        { num: 20, nome: "Noni Madueke", pos: "Atacante" },
        { num: 21, nome: "Eberechi Eze", pos: "Meio-campista" },
        { num: 22, nome: "Ivan Toney", pos: "Atacante" },
        { num: 23, nome: "James Trafford", pos: "Goleiro" },
        { num: 24, nome: "Reece James", pos: "Defensor" },
        { num: 25, nome: "Djed Spence", pos: "Defensor" },
        { num: 26, nome: "Jarell Quansah", pos: "Defensor" }
    ],
    "Irã": [
        // Fonte: Squad list oficial da FFIRI (02/06/2026) conforme ESPN.
        { num: 1, nome: "Alireza Beiranvand", pos: "Goleiro" },
        { num: 2, nome: "Payam Niazmand", pos: "Goleiro" },
        { num: 3, nome: "Hossein Hosseini", pos: "Goleiro" },
        { num: 4, nome: "Shoja Khalilzadeh", pos: "Defensor" },
        { num: 5, nome: "Mohammad Kanani", pos: "Defensor" },
        { num: 6, nome: "Hossein Kanaanizadegan", pos: "Defensor" },
        { num: 7, nome: "Ehsan Hajsafi", pos: "Defensor" },
        { num: 8, nome: "Milad Mohammadi", pos: "Defensor" },
        { num: 9, nome: "Ramin Rezaeian", pos: "Defensor" },
        { num: 10, nome: "Sadegh Moharrami", pos: "Defensor" },
        { num: 11, nome: "Saeid Ezatolahi", pos: "Meio-campista" },
        { num: 12, nome: "Ahmad Nourollahi", pos: "Meio-campista" },
        { num: 13, nome: "Saman Ghoddos", pos: "Meio-campista" },
        { num: 14, nome: "Mehdi Torabi", pos: "Meio-campista" },
        { num: 15, nome: "Ali Gholizadeh", pos: "Meio-campista" },
        { num: 16, nome: "Mohammad Mohebi", pos: "Meio-campista" },
        { num: 17, nome: "Mehdi Taremi", pos: "Atacante" },
        { num: 18, nome: "Sardar Azmoun", pos: "Atacante" },
        { num: 19, nome: "Karim Ansarifard", pos: "Atacante" },
        { num: 20, nome: "Allahyar Sayyadmanesh", pos: "Atacante" },
        { num: 21, nome: "Shahriyar Moghanlou", pos: "Atacante" }
    ],
    "Iraque": [
        // Fonte: Squad list oficial da IFA (02/06/2026) conforme ESPN.
        { num: 1, nome: "Jalal Hassan", pos: "Goleiro" },
        { num: 2, nome: "Fahad Talib", pos: "Goleiro" },
        { num: 3, nome: "Ahmed Basil", pos: "Goleiro" },
        { num: 4, nome: "Ali Adnan", pos: "Defensor" },
        { num: 5, nome: "Mustafa Nadhim", pos: "Defensor" },
        { num: 6, nome: "Ahmed Ibrahim", pos: "Defensor" },
        { num: 7, nome: "Rebin Sulaka", pos: "Defensor" },
        { num: 8, nome: "Manaf Younis", pos: "Defensor" },
        { num: 9, nome: "Merchas Doski", pos: "Defensor" },
        { num: 10, nome: "Hussein Ali", pos: "Defensor" },
        { num: 11, nome: "Safaa Hadi", pos: "Meio-campista" },
        { num: 12, nome: "Ibrahim Bayesh", pos: "Meio-campista" },
        { num: 13, nome: "Amir Al-Ammari", pos: "Meio-campista" },
        { num: 14, nome: "Osama Rashid", pos: "Meio-campista" },
        { num: 15, nome: "Bashar Resan", pos: "Meio-campista" },
        { num: 16, nome: "Youssef Amyn", pos: "Meio-campista" },
        { num: 17, nome: "Aymen Hussein", pos: "Atacante" },
        { num: 18, nome: "Ali Al-Hamadi", pos: "Atacante" },
        { num: 19, nome: "Mohanad Ali", pos: "Atacante" },
        { num: 20, nome: "Hussein Ali Al-Saedi", pos: "Atacante" },
        { num: 21, nome: "Ahmed Yasin", pos: "Atacante" }
    ],
    "Japão": [
        // Fonte: Squad list oficial da JFA (02/06/2026) conforme ESPN.
        { num: 1, nome: "Tomoki Hayakawa", pos: "Goleiro" },
        { num: 2, nome: "Keisuke Osako", pos: "Goleiro" },
        { num: 3, nome: "Zion Suzuki", pos: "Goleiro" },
        { num: 4, nome: "Ko Itakura", pos: "Defensor" },
        { num: 5, nome: "Hiroki Ito", pos: "Defensor" },
        { num: 6, nome: "Yuto Nagatomo", pos: "Defensor" },
        { num: 7, nome: "Ayumu Seko", pos: "Defensor" },
        { num: 8, nome: "Yukinari Sugawara", pos: "Defensor" },
        { num: 9, nome: "Junnosuke Suzuki", pos: "Defensor" },
        { num: 10, nome: "Shogo Taniguchi", pos: "Defensor" },
        { num: 11, nome: "Takehiro Tomiyasu", pos: "Defensor" },
        { num: 12, nome: "Tsuyoshi Watanabe", pos: "Defensor" },
        { num: 13, nome: "Ritsu Doan", pos: "Meio-campista" },
        { num: 14, nome: "Wataru Endo", pos: "Meio-campista" },
        { num: 15, nome: "Junya Ito", pos: "Meio-campista" },
        { num: 16, nome: "Daichi Kamada", pos: "Meio-campista" },
        { num: 17, nome: "Takefusa Kubo", pos: "Meio-campista" },
        { num: 18, nome: "Keito Nakamura", pos: "Meio-campista" },
        { num: 19, nome: "Kaishu Sano", pos: "Meio-campista" },
        { num: 20, nome: "Ao Tanaka", pos: "Meio-campista" },
        { num: 21, nome: "Keisuke Goto", pos: "Atacante" },
        { num: 22, nome: "Daizen Maeda", pos: "Atacante" },
        { num: 23, nome: "Koki Ogawa", pos: "Atacante" },
        { num: 24, nome: "Kento Shiogai", pos: "Atacante" },
        { num: 25, nome: "Yuito Suzuki", pos: "Atacante" },
        { num: 26, nome: "Ayase Ueda", pos: "Atacante" }
    ],
    "Marrocos": [
        // Fonte: Squad list oficial da FRMF (02/06/2026) confirmada pela FIFA.
        { num: 1, nome: "Yassine Bounou", pos: "Goleiro" },
        { num: 2, nome: "Munir El Kajoui", pos: "Goleiro" },
        { num: 3, nome: "Anas Zniti", pos: "Goleiro" },
        { num: 4, nome: "Achraf Hakimi", pos: "Defensor" },
        { num: 5, nome: "Noussair Mazraoui", pos: "Defensor" },
        { num: 6, nome: "Romain Saiss", pos: "Defensor" },
        { num: 7, nome: "Nayef Aguerd", pos: "Defensor" },
        { num: 8, nome: "Jawad El Yamiq", pos: "Defensor" },
        { num: 9, nome: "Adam Masina", pos: "Defensor" },
        { num: 10, nome: "Yahya Attiyat Allah", pos: "Defensor" },
        { num: 11, nome: "Sofyan Amrabat", pos: "Meio-campista" },
        { num: 12, nome: "Azzedine Ounahi", pos: "Meio-campista" },
        { num: 13, nome: "Bilal El Khannouss", pos: "Meio-campista" },
        { num: 14, nome: "Amine Harit", pos: "Meio-campista" },
        { num: 15, nome: "Hakim Ziyech", pos: "Atacante" },
        { num: 16, nome: "Youssef En-Nesyri", pos: "Atacante" },
        { num: 17, nome: "Sofiane Boufal", pos: "Atacante" },
        { num: 18, nome: "Ilias Chair", pos: "Atacante" },
        { num: 19, nome: "Abdessamad Ezzalzouli", pos: "Atacante" },
        { num: 20, nome: "Ez Abde", pos: "Atacante" },
        { num: 21, nome: "Amine Adli", pos: "Atacante" }
    ],
    "México": [
        // Fonte: Squad list oficial da FMF (02/06/2026). Números oficiais anunciados pela FMF em 02/06/2026.
        { num: 1, nome: "Raúl Rangel", pos: "Goleiro" },
        { num: 2, nome: "Jorge Sánchez", pos: "Defensor" },
        { num: 3, nome: "César Montes", pos: "Defensor" },
        { num: 4, nome: "Edson Álvarez", pos: "Defensor" },
        { num: 5, nome: "Johan Vásquez", pos: "Defensor" },
        { num: 6, nome: "Erik Lira", pos: "Meio-campista" },
        { num: 7, nome: "Guillermo Martínez", pos: "Atacante" },
        { num: 8, nome: "Carlos Acevedo", pos: "Goleiro" },
        { num: 9, nome: "Santiago Giménez", pos: "Atacante" },
        { num: 10, nome: "Guillermo Ochoa", pos: "Goleiro" },
        { num: 11, nome: "Jesús Gallardo", pos: "Defensor" },
        { num: 12, nome: "Mateo Chávez", pos: "Defensor" },
        { num: 13, nome: "Luis Romo", pos: "Meio-campista" },
        { num: 14, nome: "Roberto Alvarado", pos: "Meio-campista" },
        { num: 15, nome: "Israel Reyes", pos: "Defensor" },
        { num: 16, nome: "Orbelín Pineda", pos: "Meio-campista" },
        { num: 17, nome: "César Huerta", pos: "Atacante" },
        { num: 18, nome: "Julián Quiñones", pos: "Atacante" },
        { num: 19, nome: "Álvaro Fidalgo", pos: "Meio-campista" },
        { num: 20, nome: "Armando González", pos: "Atacante" },
        { num: 21, nome: "Brian Gutiérrez", pos: "Meio-campista" },
        { num: 22, nome: "Raúl Jiménez", pos: "Atacante" },
        { num: 23, nome: "Gilberto Mora", pos: "Meio-campista" },
        { num: 24, nome: "Obed Vargas", pos: "Meio-campista" },
        { num: 25, nome: "Alexis Vega", pos: "Atacante" },
        { num: 26, nome: "Luis Chávez", pos: "Meio-campista" }
    ],
    "Noruega": [
        // Fonte: Squad list oficial da NFF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Orjan Nyland", pos: "Goleiro" },
        { num: 2, nome: "Egil Selvik", pos: "Goleiro" },
        { num: 3, nome: "Mads Christiansen", pos: "Goleiro" },
        { num: 4, nome: "Kristoffer Ajer", pos: "Defensor" },
        { num: 5, nome: "Leo Ostigard", pos: "Defensor" },
        { num: 6, nome: "Andreas Hanche-Olsen", pos: "Defensor" },
        { num: 7, nome: "Marcus Holmgren Pedersen", pos: "Defensor" },
        { num: 8, nome: "Fredrik Andre Bjorkan", pos: "Defensor" },
        { num: 9, nome: "Birger Meling", pos: "Defensor" },
        { num: 10, nome: "David Moller Wolfe", pos: "Defensor" },
        { num: 11, nome: "Martin Odegaard", pos: "Meio-campista" },
        { num: 12, nome: "Sander Berge", pos: "Meio-campista" },
        { num: 13, nome: "Patrick Berg", pos: "Meio-campista" },
        { num: 14, nome: "Morten Thorsby", pos: "Meio-campista" },
        { num: 15, nome: "Kristian Thorstvedt", pos: "Meio-campista" },
        { num: 16, nome: "Hugo Vetlesen", pos: "Meio-campista" },
        { num: 17, nome: "Erling Haaland", pos: "Atacante" },
        { num: 18, nome: "Alexander Sorloth", pos: "Atacante" },
        { num: 19, nome: "Jorgen Strand Larsen", pos: "Atacante" },
        { num: 20, nome: "Oscar Bobb", pos: "Atacante" },
        { num: 21, nome: "Antonio Nusa", pos: "Atacante" }
    ],
    "Nova Zelândia": [
        // Fonte: Squad list oficial da NZF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Max Crocombe", pos: "Goleiro" },
        { num: 2, nome: "Alex Paulsen", pos: "Goleiro" },
        { num: 3, nome: "Oli Sail", pos: "Goleiro" },
        { num: 4, nome: "Nando Pijnaker", pos: "Defensor" },
        { num: 5, nome: "Bill Tuiloma", pos: "Defensor" },
        { num: 6, nome: "Tommy Smith", pos: "Defensor" },
        { num: 7, nome: "Michael Boxall", pos: "Defensor" },
        { num: 8, nome: "Francis de Vries", pos: "Defensor" },
        { num: 9, nome: "Liberato Cacace", pos: "Defensor" },
        { num: 10, nome: "Tim Payne", pos: "Defensor" },
        { num: 11, nome: "Joe Bell", pos: "Meio-campista" },
        { num: 12, nome: "Matthew Garbett", pos: "Meio-campista" },
        { num: 13, nome: "Marko Stamenic", pos: "Meio-campista" },
        { num: 14, nome: "Callum McCowatt", pos: "Meio-campista" },
        { num: 15, nome: "Elijah Just", pos: "Meio-campista" },
        { num: 16, nome: "Kosta Barbarouses", pos: "Atacante" },
        { num: 17, nome: "Chris Wood", pos: "Atacante" },
        { num: 18, nome: "Ben Waine", pos: "Atacante" },
        { num: 19, nome: "Max Mata", pos: "Atacante" }
    ],
    "Portugal": [
        // Fonte: Lista oficial da FPF divulgada em 19/05/2026. Números oficiais divulgados pela FPF e imprensa (Record) em 03/06/2026.
        { num: 1, nome: "Diogo Costa", pos: "Goleiro" },
        { num: 2, nome: "Diogo Dalot", pos: "Defensor" },
        { num: 3, nome: "Nuno Mendes", pos: "Defensor" },
        { num: 4, nome: "Ruben Dias", pos: "Defensor" },
        { num: 5, nome: "Joao Cancelo", pos: "Defensor" },
        { num: 6, nome: "Goncalo Inacio", pos: "Defensor" },
        { num: 7, nome: "Cristiano Ronaldo", pos: "Atacante" },
        { num: 8, nome: "Bruno Fernandes", pos: "Meio-campista" },
        { num: 9, nome: "Nelson Semedo", pos: "Defensor" },
        { num: 10, nome: "Bernardo Silva", pos: "Meio-campista" },
        { num: 11, nome: "Matheus Nunes", pos: "Meio-campista" },
        { num: 12, nome: "Jose Sa", pos: "Goleiro" },
        { num: 13, nome: "Joao Neves", pos: "Meio-campista" },
        { num: 14, nome: "Ruben Neves", pos: "Meio-campista" },
        { num: 15, nome: "Vitinha", pos: "Meio-campista" },
        { num: 16, nome: "Rui Silva", pos: "Goleiro" },
        { num: 17, nome: "Francisco Trincao", pos: "Atacante" },
        { num: 18, nome: "Rafael Leao", pos: "Atacante" },
        { num: 19, nome: "Joao Felix", pos: "Atacante" },
        { num: 20, nome: "Goncalo Ramos", pos: "Atacante" },
        { num: 21, nome: "Pedro Neto", pos: "Atacante" },
        { num: 22, nome: "Francisco Conceicao", pos: "Atacante" },
        { num: 23, nome: "Samu Costa", pos: "Meio-campista" }
    ],
    "Senegal": [
        // Fonte: Squad list oficial da FSF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Edouard Mendy", pos: "Goleiro" },
        { num: 2, nome: "Seny Dieng", pos: "Goleiro" },
        { num: 3, nome: "Mory Diaw", pos: "Goleiro" },
        { num: 4, nome: "Kalidou Koulibaly", pos: "Defensor" },
        { num: 5, nome: "Abdou Diallo", pos: "Defensor" },
        { num: 6, nome: "Youssouf Sabaly", pos: "Defensor" },
        { num: 7, nome: "Fode Ballo-Toure", pos: "Defensor" },
        { num: 8, nome: "Ismail Jakobs", pos: "Defensor" },
        { num: 9, nome: "Moussa Niakhate", pos: "Defensor" },
        { num: 10, nome: "Formose Mendy", pos: "Defensor" },
        { num: 11, nome: "Idrissa Gueye", pos: "Meio-campista" },
        { num: 12, nome: "Cheikhou Kouyate", pos: "Meio-campista" },
        { num: 13, nome: "Pape Gueye", pos: "Meio-campista" },
        { num: 14, nome: "Nampalys Mendy", pos: "Meio-campista" },
        { num: 15, nome: "Krepin Diatta", pos: "Meio-campista" },
        { num: 16, nome: "Sadio Mane", pos: "Atacante" },
        { num: 17, nome: "Ismaila Sarr", pos: "Atacante" },
        { num: 18, nome: "Boulaye Dia", pos: "Atacante" },
        { num: 19, nome: "Habib Diallo", pos: "Atacante" },
        { num: 20, nome: "Iliman Ndiaye", pos: "Atacante" },
        { num: 21, nome: "Nicolas Jackson", pos: "Atacante" }
    ],
    "Suécia": [
        // Fonte: Squad list oficial da SvFF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Robin Olsen", pos: "Goleiro" },
        { num: 2, nome: "Viktor Johansson", pos: "Goleiro" },
        { num: 3, nome: "Kristoffer Nordfeldt", pos: "Goleiro" },
        { num: 4, nome: "Victor Lindelof", pos: "Defensor" },
        { num: 5, nome: "Isak Hien", pos: "Defensor" },
        { num: 6, nome: "Ludwig Augustinsson", pos: "Defensor" },
        { num: 7, nome: "Emil Holm", pos: "Defensor" },
        { num: 8, nome: "Carl Starfelt", pos: "Defensor" },
        { num: 9, nome: "Jesper Holmstrom", pos: "Defensor" },
        { num: 10, nome: "Samuel Dahl", pos: "Defensor" },
        { num: 11, nome: "Dejan Kulusevski", pos: "Meio-campista" },
        { num: 12, nome: "Jens Cajuste", pos: "Meio-campista" },
        { num: 13, nome: "Jesper Karlstrom", pos: "Meio-campista" },
        { num: 14, nome: "Anton Saletros", pos: "Meio-campista" },
        { num: 15, nome: "Alexander Isak", pos: "Atacante" },
        { num: 16, nome: "Viktor Gyokeres", pos: "Atacante" },
        { num: 17, nome: "Emil Forsberg", pos: "Atacante" },
        { num: 18, nome: "Jesper Karlsson", pos: "Atacante" },
        { num: 19, nome: "Anthony Elanga", pos: "Atacante" }
    ],
    "Suíça": [
        // Fonte: Squad list oficial da SFV (02/06/2026). Numerais oficiais no site da SFV (Template Switzerland squad).
        { num: 1, nome: "Gregor Kobel", pos: "Goleiro" },
        { num: 2, nome: "Miro Muheim", pos: "Defensor" },
        { num: 3, nome: "Silvan Widmer", pos: "Defensor" },
        { num: 4, nome: "Nico Elvedi", pos: "Defensor" },
        { num: 5, nome: "Manuel Akanji", pos: "Defensor" },
        { num: 6, nome: "Denis Zakaria", pos: "Meio-campista" },
        { num: 7, nome: "Breel Embolo", pos: "Atacante" },
        { num: 8, nome: "Remo Freuler", pos: "Meio-campista" },
        { num: 9, nome: "Christian Fassnacht", pos: "Atacante" },
        { num: 10, nome: "Granit Xhaka", pos: "Meio-campista" },
        { num: 11, nome: "Dan Ndoye", pos: "Atacante" },
        { num: 12, nome: "Marvin Keller", pos: "Goleiro" },
        { num: 13, nome: "Ricardo Rodriguez", pos: "Defensor" },
        { num: 14, nome: "Fabian Rieder", pos: "Meio-campista" },
        { num: 15, nome: "Cedric Itten", pos: "Atacante" },
        { num: 16, nome: "Johan Manzambi", pos: "Meio-campista" },
        { num: 17, nome: "Zeki Amdouni", pos: "Atacante" },
        { num: 18, nome: "Yvon Mvogo", pos: "Goleiro" },
        { num: 19, nome: "Aurele Amenda", pos: "Defensor" },
        { num: 20, nome: "Luca Jaquez", pos: "Defensor" },
        { num: 21, nome: "Eray Comert", pos: "Defensor" }
    ],
    "Tunísia": [
        // Fonte: Squad list oficial da FTF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Bechir Ben Said", pos: "Goleiro" },
        { num: 2, nome: "Aymen Dahmen", pos: "Goleiro" },
        { num: 3, nome: "Mouez Hassen", pos: "Goleiro" },
        { num: 4, nome: "Montassar Talbi", pos: "Defensor" },
        { num: 5, nome: "Yassine Meriah", pos: "Defensor" },
        { num: 6, nome: "Dylan Bronn", pos: "Defensor" },
        { num: 7, nome: "Ali Abdi", pos: "Defensor" },
        { num: 8, nome: "Wajdi Kechrida", pos: "Defensor" },
        { num: 9, nome: "Mohamed Drager", pos: "Defensor" },
        { num: 10, nome: "Ellyes Skhiri", pos: "Meio-campista" },
        { num: 11, nome: "Aissa Laidouni", pos: "Meio-campista" },
        { num: 12, nome: "Hannibal Mejbri", pos: "Meio-campista" },
        { num: 13, nome: "Mohamed Ali Ben Romdhane", pos: "Meio-campista" },
        { num: 14, nome: "Nader Ghandri", pos: "Meio-campista" },
        { num: 15, nome: "Youssef Msakni", pos: "Atacante" },
        { num: 16, nome: "Wahbi Khazri", pos: "Atacante" },
        { num: 17, nome: "Saifeddine Jaziri", pos: "Atacante" },
        { num: 18, nome: "Elias Achouri", pos: "Atacante" },
        { num: 19, nome: "Omar Layouni", pos: "Atacante" },
        { num: 20, nome: "Sayfallah Ltaief", pos: "Atacante" }
    ]
};

// Exportação para uso em outros arquivos (se necessário)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = elencosOficiais;
}