// =========================================================
// ELENCOS OFICIAIS DA COPA DO MUNDO 2026 (jogadores.js)
// ATUALIZADO EM 10/06/2026 COM OS DADOS OFICIAIS DA FIFA
// =========================================================
const elencosOficiais = {
    "África do Sul": [
        // Fonte: Squad list oficial da FIFA (02/06/2026) conforme ESPN, Sky Sports e AP News
        { num: 1, nome: "Ronwen Williams", pos: "Goleiro" },
        { num: 2, nome: "Ricardo Goss", pos: "Goleiro" },
        { num: 3, nome: "Sipho Chaine", pos: "Goleiro" },
        { num: 4, nome: "Khuliso Mudau", pos: "Defensor" },
        { num: 5, nome: "Aubrey Modiba", pos: "Defensor" },
        { num: 6, nome: "Mbekezeli Mbokazi", pos: "Defensor" },
        { num: 7, nome: "Nkosinathi Sibisi", pos: "Defensor" },
        { num: 8, nome: "Ime Okon", pos: "Defensor" },
        { num: 9, nome: "Samukele Kabini", pos: "Defensor" },
        { num: 10, nome: "Thabang Matuludi", pos: "Defensor" },
        { num: 11, nome: "Bradley Cross", pos: "Defensor" },
        { num: 12, nome: "Olwethu Makhanya", pos: "Defensor" },
        { num: 13, nome: "Kamogelo Sebelebele", pos: "Defensor" },
        { num: 14, nome: "Khulumani Ndamane", pos: "Defensor" },
        { num: 15, nome: "Teboho Mokoena", pos: "Meio-campista" },
        { num: 16, nome: "Thalente Mbatha", pos: "Meio-campista" },
        { num: 17, nome: "Sphephelo Sithole", pos: "Meio-campista" },
        { num: 18, nome: "Jayden Adams", pos: "Meio-campista" },
        { num: 19, nome: "Evidence Makgopa", pos: "Atacante" },
        { num: 20, nome: "Lyle Foster", pos: "Atacante" },
        { num: 21, nome: "Iqraam Rayners", pos: "Atacante" },
        { num: 22, nome: "Themba Zwane", pos: "Atacante" },
        { num: 23, nome: "Oswin Appollis", pos: "Atacante" },
        { num: 24, nome: "Relebohile Mofokeng", pos: "Atacante" },
        { num: 25, nome: "Tshepang Moremi", pos: "Atacante" },
        { num: 26, nome: "Thapelo Maseko", pos: "Atacante" }
    ],
    "Alemanha": [
        // Fonte: Lista oficial da DFB divulgada em 21/05/2026 e confirmada pela FIFA. Numerais oficiais divulgados pelo jornal BILD e OneFootball.
        { num: 1, nome: "Manuel Neuer", pos: "Goleiro" },
        { num: 2, nome: "Alexander Nübel", pos: "Goleiro" },
        { num: 3, nome: "Oliver Baumann", pos: "Goleiro" },
        { num: 4, nome: "Joshua Kimmich", pos: "Defensor" },
        { num: 5, nome: "Antonio Rüdiger", pos: "Defensor" },
        { num: 6, nome: "Jonathan Tah", pos: "Defensor" },
        { num: 7, nome: "Nico Schlotterbeck", pos: "Defensor" },
        { num: 8, nome: "David Raum", pos: "Defensor" },
        { num: 9, nome: "Waldemar Anton", pos: "Defensor" },
        { num: 10, nome: "Malick Thiaw", pos: "Defensor" },
        { num: 11, nome: "Pascal Groß", pos: "Meio-campista" },
        { num: 12, nome: "Toni Kroos", pos: "Meio-campista" },
        { num: 13, nome: "Leon Goretzka", pos: "Meio-campista" },
        { num: 14, nome: "Jamal Musiala", pos: "Meio-campista" },
        { num: 15, nome: "Florian Wirtz", pos: "Meio-campista" },
        { num: 16, nome: "Felix Nmecha", pos: "Meio-campista" },
        { num: 17, nome: "Angelo Stiller", pos: "Meio-campista" },
        { num: 18, nome: "Aleksandar Pavlovic", pos: "Meio-campista" },
        { num: 19, nome: "Kai Havertz", pos: "Atacante" },
        { num: 20, nome: "Leroy Sané", pos: "Atacante" },
        { num: 21, nome: "Niclas Füllkrug", pos: "Atacante" },
        { num: 22, nome: "Deniz Undav", pos: "Atacante" },
        { num: 23, nome: "Maximilian Beier", pos: "Atacante" },
        { num: 24, nome: "Chris Führich", pos: "Atacante" },
        { num: 25, nome: "Nick Woltemade", pos: "Atacante" },
        { num: 26, nome: "Lennart Karl", pos: "Atacante" }
    ],
    "Argentina": [
        // Fonte: Lista oficial da AFA divulgada em 30/05/2026 e números oficiais divulgados pela imprensa argentina (Olé, TyC Sports) em 02/06/2026.
        { num: 1, nome: "Juan Musso", pos: "Goleiro" },
        { num: 2, nome: "Leonardo Balerdi", pos: "Defensor" },
        { num: 3, nome: "Nicolás Tagliafico", pos: "Defensor" },
        { num: 4, nome: "Gonzalo Montiel", pos: "Defensor" },
        { num: 5, nome: "Leandro Paredes", pos: "Meio-campista" },
        { num: 6, nome: "Lisandro Martínez", pos: "Defensor" },
        { num: 7, nome: "Rodrigo De Paul", pos: "Meio-campista" },
        { num: 8, nome: "Valentín Barco", pos: "Defensor" },
        { num: 9, nome: "Julián Álvarez", pos: "Atacante" },
        { num: 10, nome: "Lionel Messi", pos: "Atacante" },
        { num: 11, nome: "Giovani Lo Celso", pos: "Meio-campista" },
        { num: 12, nome: "Gerónimo Rulli", pos: "Goleiro" },
        { num: 13, nome: "Cristian Romero", pos: "Defensor" },
        { num: 14, nome: "Exequiel Palacios", pos: "Meio-campista" },
        { num: 15, nome: "Nicolás González", pos: "Atacante" },
        { num: 16, nome: "Facundo Medina", pos: "Defensor" },
        { num: 17, nome: "Giuliano Simeone", pos: "Atacante" },
        { num: 18, nome: "Nicolás Paz", pos: "Meio-campista" },
        { num: 19, nome: "Nicolás Otamendi", pos: "Defensor" },
        { num: 20, nome: "Alexis Mac Allister", pos: "Meio-campista" },
        { num: 21, nome: "José López", pos: "Atacante" },
        { num: 22, nome: "Lautaro Martínez", pos: "Atacante" },
        { num: 23, nome: "Emiliano Martínez", pos: "Goleiro" },
        { num: 24, nome: "Enzo Fernández", pos: "Meio-campista" },
        { num: 25, nome: "Nahuel Molina", pos: "Defensor" },
        { num: 26, nome: "Thiago Almada", pos: "Meio-campista" }
    ],
    "Austrália": [
        // Fonte: Squad list oficial (Football Australia, 02/06/2026) compilado pela ESPN.
        { num: 1, nome: "Mathew Ryan", pos: "Goleiro" },
        { num: 2, nome: "Paul Izzo", pos: "Goleiro" },
        { num: 3, nome: "Patrick Beach", pos: "Goleiro" },
        { num: 4, nome: "Aziz Behich", pos: "Defensor" },
        { num: 5, nome: "Jordan Bos", pos: "Defensor" },
        { num: 6, nome: "Cameron Burgess", pos: "Defensor" },
        { num: 7, nome: "Alessandro Circati", pos: "Defensor" },
        { num: 8, nome: "Milos Degenek", pos: "Defensor" },
        { num: 9, nome: "Jason Geria", pos: "Defensor" },
        { num: 10, nome: "Lucas Herrington", pos: "Defensor" },
        { num: 11, nome: "Jacob Italiano", pos: "Defensor" },
        { num: 12, nome: "Harry Souttar", pos: "Defensor" },
        { num: 13, nome: "Kai Trewin", pos: "Defensor" },
        { num: 14, nome: "Cameron Devlin", pos: "Meio-campista" },
        { num: 15, nome: "Ajdin Hrustic", pos: "Meio-campista" },
        { num: 16, nome: "Jackson Irvine", pos: "Meio-campista" },
        { num: 17, nome: "Connor Metcalfe", pos: "Meio-campista" },
        { num: 18, nome: "Aiden O'Neill", pos: "Meio-campista" },
        { num: 19, nome: "Paul Okon-Engstler", pos: "Meio-campista" },
        { num: 20, nome: "Nestory Irankunda", pos: "Atacante" },
        { num: 21, nome: "Mathew Leckie", pos: "Atacante" },
        { num: 22, nome: "Awer Mabil", pos: "Atacante" },
        { num: 23, nome: "Mohamed Toure", pos: "Atacante" },
        { num: 24, nome: "Nishan Velupillay", pos: "Atacante" },
        { num: 25, nome: "Cristian Volpato", pos: "Atacante" },
        { num: 26, nome: "Tete Yengi", pos: "Atacante" }
    ],
    "Áustria": [
        // Fonte: Squad list oficial da ÖFB (02/06/2026) conforme ESPN.
        { num: 1, nome: "Patrick Pentz", pos: "Goleiro" },
        { num: 2, nome: "Alexander Schlager", pos: "Goleiro" },
        { num: 3, nome: "Florian Wiegele", pos: "Goleiro" },
        { num: 4, nome: "David Affengruber", pos: "Defensor" },
        { num: 5, nome: "David Alaba", pos: "Defensor" },
        { num: 6, nome: "Kevin Danso", pos: "Defensor" },
        { num: 7, nome: "Marco Friedl", pos: "Defensor" },
        { num: 8, nome: "Philipp Lienhart", pos: "Defensor" },
        { num: 9, nome: "Phillipp Mwene", pos: "Defensor" },
        { num: 10, nome: "Stefan Posch", pos: "Defensor" },
        { num: 11, nome: "Michael Svoboda", pos: "Defensor" },
        { num: 12, nome: "Alexander Prass", pos: "Meio-campista" },
        { num: 13, nome: "Christoph Baumgartner", pos: "Meio-campista" },
        { num: 14, nome: "Carney Chukwuemeka", pos: "Meio-campista" },
        { num: 15, nome: "Florian Grillitsch", pos: "Meio-campista" },
        { num: 16, nome: "Konrad Laimer", pos: "Meio-campista" },
        { num: 17, nome: "Marcel Sabitzer", pos: "Meio-campista" },
        { num: 18, nome: "Xaver Schlager", pos: "Meio-campista" },
        { num: 19, nome: "Romano Schmid", pos: "Meio-campista" },
        { num: 20, nome: "Alessandro Schopf", pos: "Meio-campista" },
        { num: 21, nome: "Nicolas Seiwald", pos: "Meio-campista" },
        { num: 22, nome: "Paul Wanner", pos: "Meio-campista" },
        { num: 23, nome: "Patrick Wimmer", pos: "Meio-campista" },
        { num: 24, nome: "Marko Arnautovic", pos: "Atacante" },
        { num: 25, nome: "Michael Gregoritsch", pos: "Atacante" },
        { num: 26, nome: "Sasa Kalajdzic", pos: "Atacante" }
    ],
    "Bélgica": [
        // Fonte: Squad list oficial da KBVB (02/06/2026) conforme ESPN. Números oficiais divulgados pela DH Les Sports+.
        { num: 1, nome: "Thibaut Courtois", pos: "Goleiro" },
        { num: 2, nome: "Senne Lammens", pos: "Goleiro" },
        { num: 3, nome: "Mike Penders", pos: "Goleiro" },
        { num: 4, nome: "Timothy Castagne", pos: "Defensor" },
        { num: 5, nome: "Zeno Debast", pos: "Defensor" },
        { num: 6, nome: "Maxim De Cuyper", pos: "Defensor" },
        { num: 7, nome: "Koni De Winter", pos: "Defensor" },
        { num: 8, nome: "Brandon Mechele", pos: "Defensor" },
        { num: 9, nome: "Thomas Meunier", pos: "Defensor" },
        { num: 10, nome: "Nathan Ngoy", pos: "Defensor" },
        { num: 11, nome: "Arthur Theate", pos: "Defensor" },
        { num: 12, nome: "Joaquin Seys", pos: "Defensor" },
        { num: 13, nome: "Kevin De Bruyne", pos: "Meio-campista" },
        { num: 14, nome: "Amadou Onana", pos: "Meio-campista" },
        { num: 15, nome: "Nicolas Raskin", pos: "Meio-campista" },
        { num: 16, nome: "Youri Tielemans", pos: "Meio-campista" },
        { num: 17, nome: "Hans Vanaken", pos: "Meio-campista" },
        { num: 18, nome: "Axel Witsel", pos: "Meio-campista" },
        { num: 19, nome: "Charles De Ketelaere", pos: "Atacante" },
        { num: 20, nome: "Jeremy Doku", pos: "Atacante" },
        { num: 21, nome: "Matias Fernandez-Pardo", pos: "Atacante" },
        { num: 22, nome: "Romelu Lukaku", pos: "Atacante" },
        { num: 23, nome: "Dodi Lukebakio", pos: "Atacante" },
        { num: 24, nome: "Diego Moreira", pos: "Atacante" },
        { num: 25, nome: "Alexis Saelemaekers", pos: "Atacante" },
        { num: 26, nome: "Leandro Trossard", pos: "Atacante" }
    ],
    "Bósnia e H.": [
        // Fonte: Squad list oficial da NFSBiH (02/06/2026) compilado pela AS.com.
        { num: 1, nome: "Nikola Vasilj", pos: "Goleiro" },
        { num: 2, nome: "Martin Zlomislic", pos: "Goleiro" },
        { num: 3, nome: "Osman Hadzikic", pos: "Goleiro" },
        { num: 4, nome: "Sead Kolasinac", pos: "Defensor" },
        { num: 5, nome: "Amar Dedic", pos: "Defensor" },
        { num: 6, nome: "Nihad Mujakic", pos: "Defensor" },
        { num: 7, nome: "Nikola Katic", pos: "Defensor" },
        { num: 8, nome: "Tarik Muharemovic", pos: "Defensor" },
        { num: 9, nome: "Stjepan Radeljic", pos: "Defensor" },
        { num: 10, nome: "Dennis Hadzikadunic", pos: "Defensor" },
        { num: 11, nome: "Nidal Celik", pos: "Defensor" },
        { num: 12, nome: "Amir Hadziahmetovic", pos: "Meio-campista" },
        { num: 13, nome: "Ivan Sunjic", pos: "Meio-campista" },
        { num: 14, nome: "Ivan Basic", pos: "Meio-campista" },
        { num: 15, nome: "Dzenis Burnic", pos: "Meio-campista" },
        { num: 16, nome: "Ermin Mahmic", pos: "Meio-campista" },
        { num: 17, nome: "Benjamin Tahirovic", pos: "Meio-campista" },
        { num: 18, nome: "Kerim Alajbegovic", pos: "Meio-campista" },
        { num: 19, nome: "Armin Gigovic", pos: "Meio-campista" },
        { num: 20, nome: "Amar Memic", pos: "Meio-campista" },
        { num: 21, nome: "Esmir Bajraktarevic", pos: "Meio-campista" },
        { num: 22, nome: "Haris Tabakovic", pos: "Atacante" },
        { num: 23, nome: "Jovo Lukic", pos: "Atacante" },
        { num: 24, nome: "Edin Dzeko", pos: "Atacante" },
        { num: 25, nome: "Ermedin Demirovic", pos: "Atacante" },
        { num: 26, nome: "Samed Bazdar", pos: "Atacante" }
    ],
    "Brasil": [
        // Fonte: Lista oficial da CBF divulgada em 19/05/2026. Números oficiais publicados pelo Olympics.com em 02/06/2026.
        { num: 1, nome: "Alisson", pos: "Goleiro" },
        { num: 2, nome: "Ederson", pos: "Meio-campista" },
        { num: 3, nome: "Gabriel Magalhães", pos: "Defensor" },
        { num: 4, nome: "Marquinhos", pos: "Defensor" },
        { num: 5, nome: "Casemiro", pos: "Meio-campista" },
        { num: 6, nome: "Alex Sandro", pos: "Defensor" },
        { num: 7, nome: "Vinícius Jr", pos: "Atacante" },
        { num: 8, nome: "Bruno Guimarães", pos: "Meio-campista" },
        { num: 9, nome: "Matheus Cunha", pos: "Atacante" },
        { num: 10, nome: "Neymar Jr", pos: "Atacante" },
        { num: 11, nome: "Raphinha", pos: "Atacante" },
        { num: 12, nome: "Weverton", pos: "Goleiro" },
        { num: 13, nome: "Danilo", pos: "Defensor" },
        { num: 14, nome: "Bremer", pos: "Defensor" },
        { num: 15, nome: "Léo Pereira", pos: "Defensor" },
        { num: 16, nome: "Douglas Santos", pos: "Defensor" },
        { num: 17, nome: "Fabinho", pos: "Meio-campista" },
        { num: 18, nome: "Danilo Santos", pos: "Meio-campista" },
        { num: 19, nome: "Endrick", pos: "Atacante" },
        { num: 20, nome: "Lucas Paquetá", pos: "Meio-campista" },
        { num: 21, nome: "Luiz Henrique", pos: "Atacante" },
        { num: 22, nome: "Gabriel Martinelli", pos: "Atacante" },
        { num: 23, nome: "Ederson", pos: "Goleiro" },
        { num: 24, nome: "Roger Ibañez", pos: "Defensor" },
        { num: 25, nome: "Igor Thiago", pos: "Atacante" },
        { num: 26, nome: "Rayan", pos: "Atacante" }
    ],
    "Canadá": [
        // Fonte: Squad list oficial da CSA (02/06/2026) conforme ESPN. Substituições pós-02/06 incluídas (e.g., Jayden Nelson).
        { num: 1, nome: "Dayne St Clair", pos: "Goleiro" },
        { num: 2, nome: "Maxime Crepeau", pos: "Goleiro" },
        { num: 3, nome: "Owen Goodman", pos: "Goleiro" },
        { num: 4, nome: "Alistair Johnston", pos: "Defensor" },
        { num: 5, nome: "Alphonso Davies", pos: "Defensor" },
        { num: 6, nome: "Moise Bombito", pos: "Defensor" },
        { num: 7, nome: "Derek Cornelius", pos: "Defensor" },
        { num: 8, nome: "Luc de Fougerolles", pos: "Defensor" },
        { num: 9, nome: "Richie Laryea", pos: "Defensor" },
        { num: 10, nome: "Alfie Jones", pos: "Defensor" },
        { num: 11, nome: "Niko Sigur", pos: "Defensor" },
        { num: 12, nome: "Joel Waterman", pos: "Defensor" },
        { num: 13, nome: "Stephen Eustaquio", pos: "Meio-campista" },
        { num: 14, nome: "Ismael Kone", pos: "Meio-campista" },
        { num: 15, nome: "Tajon Buchanan", pos: "Meio-campista" },
        { num: 16, nome: "Mathieu Choiniere", pos: "Meio-campista" },
        { num: 17, nome: "Ali Ahmed", pos: "Meio-campista" },
        { num: 18, nome: "Nathan Saliba", pos: "Meio-campista" },
        { num: 19, nome: "Liam Millar", pos: "Meio-campista" },
        { num: 20, nome: "Jonathan Osorio", pos: "Meio-campista" },
        { num: 21, nome: "Jacob Shaffelburg", pos: "Meio-campista" },
        { num: 22, nome: "Jonathan David", pos: "Atacante" },
        { num: 23, nome: "Cyle Larin", pos: "Atacante" },
        { num: 24, nome: "Promise David", pos: "Atacante" },
        { num: 25, nome: "Tani Oluwaseyi", pos: "Atacante" },
        { num: 26, nome: "Jayden Nelson", pos: "Atacante" }
    ],
    "Catar": [
        // Fonte: Squad list oficial da QFA (02/06/2026) compilado pela ESPN.
        { num: 1, nome: "Salah Zakaria", pos: "Goleiro" },
        { num: 2, nome: "Meshaal Barsham", pos: "Goleiro" },
        { num: 3, nome: "Mahmoud Abunada", pos: "Goleiro" },
        { num: 4, nome: "Boualem Khoukhi", pos: "Defensor" },
        { num: 5, nome: "Pedro Miguel", pos: "Defensor" },
        { num: 6, nome: "Sultan Al Brake", pos: "Defensor" },
        { num: 7, nome: "Al-Hashmi Al-Hussain", pos: "Defensor" },
        { num: 8, nome: "Ayoub Al-Alawi", pos: "Defensor" },
        { num: 9, nome: "Homam Al-Amin", pos: "Defensor" },
        { num: 10, nome: "Lucas Mendes", pos: "Defensor" },
        { num: 11, nome: "Issa Laye", pos: "Defensor" },
        { num: 12, nome: "Ahmed Fathi", pos: "Meio-campista" },
        { num: 13, nome: "Jassim Gaber", pos: "Meio-campista" },
        { num: 14, nome: "Assim Madibo", pos: "Meio-campista" },
        { num: 15, nome: "Abdulaziz Hatem", pos: "Meio-campista" },
        { num: 16, nome: "Karim Boudiaf", pos: "Meio-campista" },
        { num: 17, nome: "Mohammed Mannai", pos: "Meio-campista" },
        { num: 18, nome: "Akram Afif", pos: "Atacante" },
        { num: 19, nome: "Almoez Ali", pos: "Atacante" },
        { num: 20, nome: "Tahsin", pos: "Atacante" }
        // Nota: Elenco do Catar registrado com 20 jogadores conforme lista oficial.
    ],
    "Colômbia": [
        // Fonte: Squad list oficial da FCF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Camilo Vargas", pos: "Goleiro" },
        { num: 2, nome: "Alvaro Montero", pos: "Goleiro" },
        { num: 3, nome: "David Ospina", pos: "Goleiro" },
        { num: 4, nome: "Davinson Sanchez", pos: "Defensor" },
        { num: 5, nome: "Jhon Lucumi", pos: "Defensor" },
        { num: 6, nome: "Yerry Mina", pos: "Defensor" },
        { num: 7, nome: "Willer Ditta", pos: "Defensor" },
        { num: 8, nome: "Daniel Munoz", pos: "Defensor" },
        { num: 9, nome: "Santiago Arias", pos: "Defensor" },
        { num: 10, nome: "Johan Mojica", pos: "Defensor" },
        { num: 11, nome: "Deiver Machado", pos: "Defensor" },
        { num: 12, nome: "Jefferson Lerma", pos: "Meio-campista" },
        { num: 13, nome: "Richard Rios", pos: "Meio-campista" },
        { num: 14, nome: "James Rodriguez", pos: "Meio-campista" },
        { num: 15, nome: "Juan Fernando Quintero", pos: "Meio-campista" },
        { num: 16, nome: "Jhon Arias", pos: "Meio-campista" },
        { num: 17, nome: "Luis Diaz", pos: "Atacante" },
        { num: 18, nome: "Rafael Santos Borre", pos: "Atacante" },
        { num: 19, nome: "Jhon Duran", pos: "Atacante" },
        { num: 20, nome: "Mateo Cassierra", pos: "Atacante" },
        { num: 21, nome: "Yaser Asprilla", pos: "Atacante" },
        { num: 22, nome: "Luis Sinisterra", pos: "Atacante" }
    ],
    "Coreia do Sul": [
        // Fonte: Lista oficial da KFA. Números oficiais divulgados pela imprensa sul-coreana (Naver Sports) em 11/06/2026.
        { num: 1, nome: "Kim Seunggyu", pos: "Goleiro" },
        { num: 21, nome: "Jo Hyeonwoo", pos: "Goleiro" },
        { num: 12, nome: "Song Bumkeun", pos: "Goleiro" },
        { num: 4, nome: "Kim Minjae", pos: "Defensor" },
        { num: 15, nome: "Kim Moonhwan", pos: "Defensor" },
        { num: 5, nome: "Kim Taehyeon", pos: "Defensor" },
        { num: 16, nome: "Park Jinseob", pos: "Defensor" },
        { num: 22, nome: "Seol Youngwoo", pos: "Defensor" },
        { num: 23, nome: "Jens Castrop", pos: "Defensor" },
        { num: 3, nome: "Lee Gihyuk", pos: "Defensor" },
        { num: 13, nome: "Lee Taeseok", pos: "Defensor" },
        { num: 2, nome: "Lee Hanbeom", pos: "Defensor" },
        { num: 14, nome: "Cho Wi-je", pos: "Defensor" },
        { num: 24, nome: "Kim Jingyu", pos: "Meio-campista" },
        { num: 17, nome: "Bae Junho", pos: "Meio-campista" },
        { num: 8, nome: "Paik Seungho", pos: "Meio-campista" },
        { num: 20, nome: "Yang Hyunjun", pos: "Meio-campista" },
        { num: 25, nome: "Eom Jisung", pos: "Meio-campista" },
        { num: 19, nome: "Lee Kangin", pos: "Meio-campista" },
        { num: 26, nome: "Lee Donggyeong", pos: "Meio-campista" },
        { num: 10, nome: "Lee Jaesung", pos: "Meio-campista" },
        { num: 6, nome: "Hwang Inbeom", pos: "Meio-campista" },
        { num: 11, nome: "Hwang Heechan", pos: "Meio-campista" },
        { num: 7, nome: "Son Heungmin", pos: "Atacante" },
        { num: 18, nome: "Oh Hyeongyu", pos: "Atacante" },
        { num: 9, nome: "Cho Gue sung", pos: "Atacante" }
    ],
    "Costa do Marfim": [
        // Fonte: Squad list oficial da FIF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Yahia Fofana", pos: "Goleiro" },
        { num: 2, nome: "Badra Ali Sangare", pos: "Goleiro" },
        { num: 3, nome: "Ira Tape", pos: "Goleiro" },
        { num: 4, nome: "Evan Ndicka", pos: "Defensor" },
        { num: 5, nome: "Odilon Kossounou", pos: "Defensor" },
        { num: 6, nome: "Willy Boly", pos: "Defensor" },
        { num: 7, nome: "Ousmane Diomande", pos: "Defensor" },
        { num: 8, nome: "Emerse Fae", pos: "Defensor" },
        { num: 9, nome: "Ghislain Konan", pos: "Defensor" },
        { num: 10, nome: "Wilfried Singo", pos: "Defensor" },
        { num: 11, nome: "Serge Aurier", pos: "Defensor" },
        { num: 12, nome: "Franck Kessie", pos: "Meio-campista" },
        { num: 13, nome: "Seko Fofana", pos: "Meio-campista" },
        { num: 14, nome: "Ibrahima Sangare", pos: "Meio-campista" },
        { num: 15, nome: "Hamed Traore", pos: "Meio-campista" },
        { num: 16, nome: "Jean Michael Seri", pos: "Meio-campista" },
        { num: 17, nome: "Simon Adingra", pos: "Atacante" },
        { num: 18, nome: "Sebastien Haller", pos: "Atacante" },
        { num: 19, nome: "Nicolas Pepe", pos: "Atacante" },
        { num: 20, nome: "Jeremie Boga", pos: "Atacante" },
        { num: 21, nome: "Christian Kouame", pos: "Atacante" },
        { num: 22, nome: "Max Gradel", pos: "Atacante" }
    ],
    "Croácia": [
        // Fonte: Squad list oficial da HNS (18/05/2026) confirmada pela FIFA. Numerais oficiais no site da HNS.
        { num: 1, nome: "Dominik Livakovic", pos: "Goleiro" },
        { num: 2, nome: "Ivor Pandur", pos: "Goleiro" },
        { num: 3, nome: "Dominik Kotarski", pos: "Goleiro" },
        { num: 4, nome: "Josip Stanisic", pos: "Defensor" },
        { num: 5, nome: "Marin Pongracic", pos: "Defensor" },
        { num: 6, nome: "Josko Gvardiol", pos: "Defensor" },
        { num: 7, nome: "Josip Sutalo", pos: "Defensor" },
        { num: 8, nome: "Duje Caleta-Car", pos: "Defensor" },
        { num: 9, nome: "Borna Sosa", pos: "Defensor" },
        { num: 10, nome: "Josip Juranovic", pos: "Defensor" },
        { num: 11, nome: "Luka Modric", pos: "Meio-campista" },
        { num: 12, nome: "Mateo Kovacic", pos: "Meio-campista" },
        { num: 13, nome: "Mario Pasalic", pos: "Meio-campista" },
        { num: 14, nome: "Luka Sucic", pos: "Meio-campista" },
        { num: 15, nome: "Martin Baturina", pos: "Meio-campista" },
        { num: 16, nome: "Nikola Vlasic", pos: "Meio-campista" },
        { num: 17, nome: "Petar Sucic", pos: "Meio-campista" },
        { num: 18, nome: "Ivan Perisic", pos: "Atacante" },
        { num: 19, nome: "Andrej Kramaric", pos: "Atacante" },
        { num: 20, nome: "Bruno Petkovic", pos: "Atacante" },
        { num: 21, nome: "Igor Matanovic", pos: "Atacante" },
        { num: 22, nome: "Dion Drena Beljo", pos: "Atacante" }
    ],
    "Escócia": [
        // Fonte: Squad list oficial da SFA (02/06/2026) conforme ESPN.
        { num: 1, nome: "Angus Gunn", pos: "Goleiro" },
        { num: 2, nome: "Zander Clark", pos: "Goleiro" },
        { num: 3, nome: "Liam Kelly", pos: "Goleiro" },
        { num: 4, nome: "Andy Robertson", pos: "Defensor" },
        { num: 5, nome: "Kieran Tierney", pos: "Defensor" },
        { num: 6, nome: "Grant Hanley", pos: "Defensor" },
        { num: 7, nome: "Ryan Porteous", pos: "Defensor" },
        { num: 8, nome: "Jack Hendry", pos: "Defensor" },
        { num: 9, nome: "Scott McKenna", pos: "Defensor" },
        { num: 10, nome: "Nathan Patterson", pos: "Defensor" },
        { num: 11, nome: "Scott McTominay", pos: "Meio-campista" },
        { num: 12, nome: "John McGinn", pos: "Meio-campista" },
        { num: 13, nome: "Callum McGregor", pos: "Meio-campista" },
        { num: 14, nome: "Billy Gilmour", pos: "Meio-campista" },
        { num: 15, nome: "Ryan Christie", pos: "Meio-campista" },
        { num: 16, nome: "Lewis Ferguson", pos: "Meio-campista" },
        { num: 17, nome: "Stuart Armstrong", pos: "Meio-campista" },
        { num: 18, nome: "Kenny McLean", pos: "Meio-campista" },
        { num: 19, nome: "Lyndon Dykes", pos: "Atacante" },
        { num: 20, nome: "Che Adams", pos: "Atacante" },
        { num: 21, nome: "Ryan Fraser", pos: "Atacante" },
        { num: 22, nome: "Kevin Nisbet", pos: "Atacante" },
        { num: 23, nome: "Lawrence Shankland", pos: "Atacante" }
    ],
    "Egito": [
        // Fonte: Squad list oficial da EFA (02/06/2026) conforme ESPN.
        { num: 1, nome: "Mohamed El Shenawy", pos: "Goleiro" },
        { num: 2, nome: "Mohamed Abou Gabal", pos: "Goleiro" },
        { num: 3, nome: "Ahmed El Shenawy", pos: "Goleiro" },
        { num: 4, nome: "Ahmed Hegazy", pos: "Defensor" },
        { num: 5, nome: "Ali Gabr", pos: "Defensor" },
        { num: 6, nome: "Mohamed Abdelmonem", pos: "Defensor" },
        { num: 7, nome: "Mahmoud Hamdy", pos: "Defensor" },
        { num: 8, nome: "Omar Kamal", pos: "Defensor" },
        { num: 9, nome: "Ahmed Fatouh", pos: "Defensor" },
        { num: 10, nome: "Mohamed Hany", pos: "Defensor" },
        { num: 11, nome: "Emam Ashour", pos: "Meio-campista" },
        { num: 12, nome: "Mohamed Elneny", pos: "Meio-campista" },
        { num: 13, nome: "Tarek Hamed", pos: "Meio-campista" },
        { num: 14, nome: "Hamdi Fathi", pos: "Meio-campista" },
        { num: 15, nome: "Marwan Attia", pos: "Meio-campista" },
        { num: 16, nome: "Nabil Emad", pos: "Meio-campista" },
        { num: 17, nome: "Mohamed Salah", pos: "Atacante" },
        { num: 18, nome: "Mostafa Mohamed", pos: "Atacante" },
        { num: 19, nome: "Mahmoud Trezeguet", pos: "Atacante" },
        { num: 20, nome: "Omar Marmoush", pos: "Atacante" },
        { num: 21, nome: "Mohamed Sherif", pos: "Atacante" },
        { num: 22, nome: "Zizo", pos: "Atacante" },
        { num: 23, nome: "Ibrahim Adel", pos: "Atacante" }
    ],
    "Espanha": [
        // Fonte: Lista oficial da RFEF divulgada em 25/05/2026. Numerais oficiais não divulgados por clubes; numeração sequencial aplicada.
        { num: 1, nome: "Unai Simon", pos: "Goleiro" },
        { num: 2, nome: "David Raya", pos: "Goleiro" },
        { num: 3, nome: "Joan Garcia", pos: "Goleiro" },
        { num: 4, nome: "Marcos Llorente", pos: "Defensor" },
        { num: 5, nome: "Marc Cucurella", pos: "Defensor" },
        { num: 6, nome: "Alejandro Grimaldo", pos: "Defensor" },
        { num: 7, nome: "Pedro Porro", pos: "Defensor" },
        { num: 8, nome: "Pau Cubarsi", pos: "Defensor" },
        { num: 9, nome: "Aymeric Laporte", pos: "Defensor" },
        { num: 10, nome: "Marc Pubill", pos: "Defensor" },
        { num: 11, nome: "Eric Garcia", pos: "Defensor" },
        { num: 12, nome: "Rodri", pos: "Meio-campista" },
        { num: 13, nome: "Martin Zubimendi", pos: "Meio-campista" },
        { num: 14, nome: "Pedri", pos: "Meio-campista" },
        { num: 15, nome: "Fabian Ruiz", pos: "Meio-campista" },
        { num: 16, nome: "Mikel Merino", pos: "Meio-campista" },
        { num: 17, nome: "Gavi", pos: "Meio-campista" },
        { num: 18, nome: "Alex Baena", pos: "Meio-campista" },
        { num: 19, nome: "Nico Williams", pos: "Atacante" },
        { num: 20, nome: "Dani Olmo", pos: "Atacante" },
        { num: 21, nome: "Ferran Torres", pos: "Atacante" },
        { num: 22, nome: "Mikel Oyarzabal", pos: "Atacante" },
        { num: 23, nome: "Lamine Yamal", pos: "Atacante" },
        { num: 24, nome: "Borja Iglesias", pos: "Atacante" },
        { num: 25, nome: "Victor Munoz", pos: "Atacante" },
        { num: 26, nome: "Yeremy Pino", pos: "Atacante" }
    ],
    "EUA": [
        // Fonte: Squad list oficial da USSF (26/05/2026). Números oficiais anunciados pela US Soccer em 29/05/2026.
        { num: 1, nome: "Matt Turner", pos: "Goleiro" },
        { num: 2, nome: "Sergino Dest", pos: "Defensor" },
        { num: 3, nome: "Alex Freeman", pos: "Defensor" },
        { num: 4, nome: "Tyler Adams", pos: "Meio-campista" },
        { num: 5, nome: "Joe Scally", pos: "Defensor" },
        { num: 6, nome: "Miles Robinson", pos: "Defensor" },
        { num: 7, nome: "Gio Reyna", pos: "Meio-campista" },
        { num: 8, nome: "Weston McKennie", pos: "Meio-campista" },
        { num: 9, nome: "Folarin Balogun", pos: "Atacante" },
        { num: 10, nome: "Christian Pulisic", pos: "Atacante" },
        { num: 11, nome: "Brenden Aaronson", pos: "Meio-campista" },
        { num: 12, nome: "Ricardo Pepi", pos: "Atacante" },
        { num: 13, nome: "Tim Ream", pos: "Defensor" },
        { num: 14, nome: "Mark McKenzie", pos: "Defensor" },
        { num: 15, nome: "Cristian Roldan", pos: "Meio-campista" },
        { num: 16, nome: "Antonee Robinson", pos: "Defensor" },
        { num: 17, nome: "Tim Weah", pos: "Atacante" },
        { num: 18, nome: "Malik Tillman", pos: "Meio-campista" },
        { num: 19, nome: "Haji Wright", pos: "Atacante" },
        { num: 20, nome: "Matt Freese", pos: "Goleiro" },
        { num: 21, nome: "Chris Brady", pos: "Goleiro" },
        { num: 22, nome: "Max Arfsten", pos: "Meio-campista" }
    ],
    "França": [
        // Fonte: Lista oficial da FFF divulgada em 14/05/2026. Números oficiais publicados pela FFF e imprensa (L'Équipe) em 02/06/2026.
        { num: 1, nome: "Brice Samba", pos: "Goleiro" },
        { num: 2, nome: "Malo Gusto", pos: "Defensor" },
        { num: 3, nome: "Lucas Digne", pos: "Defensor" },
        { num: 4, nome: "Dayot Upamecano", pos: "Defensor" },
        { num: 5, nome: "Jules Koundé", pos: "Defensor" },
        { num: 6, nome: "Manu Koné", pos: "Meio-campista" },
        { num: 7, nome: "Ousmane Dembélé", pos: "Atacante" },
        { num: 8, nome: "Aurélien Tchouaméni", pos: "Meio-campista" },
        { num: 9, nome: "Marcus Thuram", pos: "Atacante" },
        { num: 10, nome: "Kylian Mbappé", pos: "Atacante" },
        { num: 11, nome: "Michael Olise", pos: "Atacante" },
        { num: 12, nome: "Bradley Barcola", pos: "Atacante" },
        { num: 13, nome: "N'Golo Kanté", pos: "Meio-campista" },
        { num: 14, nome: "Adrien Rabiot", pos: "Meio-campista" },
        { num: 15, nome: "Ibrahima Konaté", pos: "Defensor" },
        { num: 16, nome: "Mike Maignan", pos: "Goleiro" },
        { num: 17, nome: "William Saliba", pos: "Defensor" },
        { num: 18, nome: "Warren Zaïre-Emery", pos: "Meio-campista" },
        { num: 19, nome: "Theo Hernandez", pos: "Defensor" },
        { num: 20, nome: "Désiré Doué", pos: "Atacante" },
        { num: 21, nome: "Lucas Hernandez", pos: "Defensor" },
        { num: 22, nome: "Jean-Philippe Mateta", pos: "Atacante" },
        { num: 23, nome: "Robin Risser", pos: "Goleiro" },
        { num: 24, nome: "Rayan Cherki", pos: "Atacante" },
        { num: 25, nome: "Maghnes Akliouche", pos: "Atacante" },
        { num: 26, nome: "Maxence Lacroix", pos: "Defensor" }
    ],
    "Holanda": [
        // Fonte: Squad list oficial da KNVB divulgada em 27/05/2026. Numerais não divulgados oficialmente; numeração sequencial aplicada.
        { num: 1, nome: "Bart Verbruggen", pos: "Goleiro" },
        { num: 2, nome: "Mark Flekken", pos: "Goleiro" },
        { num: 3, nome: "Robin Roefs", pos: "Goleiro" },
        { num: 4, nome: "Virgil van Dijk", pos: "Defensor" },
        { num: 5, nome: "Nathan Ake", pos: "Defensor" },
        { num: 6, nome: "Jurrien Timber", pos: "Defensor" },
        { num: 7, nome: "Micky van de Ven", pos: "Defensor" },
        { num: 8, nome: "Denzel Dumfries", pos: "Defensor" },
        { num: 9, nome: "Jorrel Hato", pos: "Defensor" },
        { num: 10, nome: "Jan Paul van Hecke", pos: "Defensor" },
        { num: 11, nome: "Frenkie de Jong", pos: "Meio-campista" },
        { num: 12, nome: "Tijjani Reijnders", pos: "Meio-campista" },
        { num: 13, nome: "Ryan Gravenberch", pos: "Meio-campista" },
        { num: 14, nome: "Quinten Timber", pos: "Meio-campista" },
        { num: 15, nome: "Mats Wieffer", pos: "Meio-campista" },
        { num: 16, nome: "Guus Til", pos: "Meio-campista" },
        { num: 17, nome: "Memphis Depay", pos: "Atacante" },
        { num: 18, nome: "Cody Gakpo", pos: "Atacante" },
        { num: 19, nome: "Brian Brobbey", pos: "Atacante" },
        { num: 20, nome: "Noa Lang", pos: "Atacante" },
        { num: 21, nome: "Donyell Malen", pos: "Atacante" },
        { num: 22, nome: "Justin Kluivert", pos: "Atacante" },
        { num: 23, nome: "Crysencio Summerville", pos: "Atacante" }
    ],
    "Inglaterra": [
        // Fonte: Lista oficial da FA divulgada em 22/05/2026. Números oficiais divulgados pela FA em 02/06/2026.
        { num: 1, nome: "Jordan Pickford", pos: "Goleiro" },
        { num: 2, nome: "Ezri Konsa", pos: "Defensor" },
        { num: 3, nome: "Nico O'Reilly", pos: "Defensor" },
        { num: 4, nome: "Declan Rice", pos: "Meio-campista" },
        { num: 5, nome: "John Stones", pos: "Defensor" },
        { num: 6, nome: "Marc Guehi", pos: "Defensor" },
        { num: 7, nome: "Bukayo Saka", pos: "Atacante" },
        { num: 8, nome: "Elliot Anderson", pos: "Meio-campista" },
        { num: 9, nome: "Harry Kane", pos: "Atacante" },
        { num: 10, nome: "Jude Bellingham", pos: "Atacante" },
        { num: 11, nome: "Marcus Rashford", pos: "Atacante" },
        { num: 12, nome: "Tino Livramento", pos: "Defensor" },
        { num: 13, nome: "Dean Henderson", pos: "Goleiro" },
        { num: 14, nome: "Jordan Henderson", pos: "Meio-campista" },
        { num: 15, nome: "Dan Burn", pos: "Defensor" },
        { num: 16, nome: "Kobbie Mainoo", pos: "Meio-campista" },
        { num: 17, nome: "Morgan Rogers", pos: "Meio-campista" },
        { num: 18, nome: "Anthony Gordon", pos: "Atacante" },
        { num: 19, nome: "Ollie Watkins", pos: "Atacante" },
        { num: 20, nome: "Noni Madueke", pos: "Atacante" },
        { num: 21, nome: "Eberechi Eze", pos: "Meio-campista" },
        { num: 22, nome: "Ivan Toney", pos: "Atacante" },
        { num: 23, nome: "James Trafford", pos: "Goleiro" },
        { num: 24, nome: "Reece James", pos: "Defensor" },
        { num: 25, nome: "Djed Spence", pos: "Defensor" },
        { num: 26, nome: "Jarell Quansah", pos: "Defensor" }
    ],
    "Irã": [
        // Fonte: Squad list oficial da FFIRI (02/06/2026) conforme ESPN.
        { num: 1, nome: "Alireza Beiranvand", pos: "Goleiro" },
        { num: 2, nome: "Payam Niazmand", pos: "Goleiro" },
        { num: 3, nome: "Hossein Hosseini", pos: "Goleiro" },
        { num: 4, nome: "Shoja Khalilzadeh", pos: "Defensor" },
        { num: 5, nome: "Mohammad Kanani", pos: "Defensor" },
        { num: 6, nome: "Hossein Kanaanizadegan", pos: "Defensor" },
        { num: 7, nome: "Ehsan Hajsafi", pos: "Defensor" },
        { num: 8, nome: "Milad Mohammadi", pos: "Defensor" },
        { num: 9, nome: "Ramin Rezaeian", pos: "Defensor" },
        { num: 10, nome: "Sadegh Moharrami", pos: "Defensor" },
        { num: 11, nome: "Saeid Ezatolahi", pos: "Meio-campista" },
        { num: 12, nome: "Ahmad Nourollahi", pos: "Meio-campista" },
        { num: 13, nome: "Saman Ghoddos", pos: "Meio-campista" },
        { num: 14, nome: "Mehdi Torabi", pos: "Meio-campista" },
        { num: 15, nome: "Ali Gholizadeh", pos: "Meio-campista" },
        { num: 16, nome: "Mohammad Mohebi", pos: "Meio-campista" },
        { num: 17, nome: "Mehdi Taremi", pos: "Atacante" },
        { num: 18, nome: "Sardar Azmoun", pos: "Atacante" },
        { num: 19, nome: "Karim Ansarifard", pos: "Atacante" },
        { num: 20, nome: "Allahyar Sayyadmanesh", pos: "Atacante" },
        { num: 21, nome: "Shahriyar Moghanlou", pos: "Atacante" }
    ],
    "Iraque": [
        // Fonte: Squad list oficial da IFA (02/06/2026) conforme ESPN.
        { num: 1, nome: "Jalal Hassan", pos: "Goleiro" },
        { num: 2, nome: "Fahad Talib", pos: "Goleiro" },
        { num: 3, nome: "Ahmed Basil", pos: "Goleiro" },
        { num: 4, nome: "Ali Adnan", pos: "Defensor" },
        { num: 5, nome: "Mustafa Nadhim", pos: "Defensor" },
        { num: 6, nome: "Ahmed Ibrahim", pos: "Defensor" },
        { num: 7, nome: "Rebin Sulaka", pos: "Defensor" },
        { num: 8, nome: "Manaf Younis", pos: "Defensor" },
        { num: 9, nome: "Merchas Doski", pos: "Defensor" },
        { num: 10, nome: "Hussein Ali", pos: "Defensor" },
        { num: 11, nome: "Safaa Hadi", pos: "Meio-campista" },
        { num: 12, nome: "Ibrahim Bayesh", pos: "Meio-campista" },
        { num: 13, nome: "Amir Al-Ammari", pos: "Meio-campista" },
        { num: 14, nome: "Osama Rashid", pos: "Meio-campista" },
        { num: 15, nome: "Bashar Resan", pos: "Meio-campista" },
        { num: 16, nome: "Youssef Amyn", pos: "Meio-campista" },
        { num: 17, nome: "Aymen Hussein", pos: "Atacante" },
        { num: 18, nome: "Ali Al-Hamadi", pos: "Atacante" },
        { num: 19, nome: "Mohanad Ali", pos: "Atacante" },
        { num: 20, nome: "Hussein Ali Al-Saedi", pos: "Atacante" },
        { num: 21, nome: "Ahmed Yasin", pos: "Atacante" }
    ],
    "Japão": [
        // Fonte: Squad list oficial da JFA (02/06/2026) conforme ESPN.
        { num: 1, nome: "Tomoki Hayakawa", pos: "Goleiro" },
        { num: 2, nome: "Keisuke Osako", pos: "Goleiro" },
        { num: 3, nome: "Zion Suzuki", pos: "Goleiro" },
        { num: 4, nome: "Ko Itakura", pos: "Defensor" },
        { num: 5, nome: "Hiroki Ito", pos: "Defensor" },
        { num: 6, nome: "Yuto Nagatomo", pos: "Defensor" },
        { num: 7, nome: "Ayumu Seko", pos: "Defensor" },
        { num: 8, nome: "Yukinari Sugawara", pos: "Defensor" },
        { num: 9, nome: "Junnosuke Suzuki", pos: "Defensor" },
        { num: 10, nome: "Shogo Taniguchi", pos: "Defensor" },
        { num: 11, nome: "Takehiro Tomiyasu", pos: "Defensor" },
        { num: 12, nome: "Tsuyoshi Watanabe", pos: "Defensor" },
        { num: 13, nome: "Ritsu Doan", pos: "Meio-campista" },
        { num: 14, nome: "Wataru Endo", pos: "Meio-campista" },
        { num: 15, nome: "Junya Ito", pos: "Meio-campista" },
        { num: 16, nome: "Daichi Kamada", pos: "Meio-campista" },
        { num: 17, nome: "Takefusa Kubo", pos: "Meio-campista" },
        { num: 18, nome: "Keito Nakamura", pos: "Meio-campista" },
        { num: 19, nome: "Kaishu Sano", pos: "Meio-campista" },
        { num: 20, nome: "Ao Tanaka", pos: "Meio-campista" },
        { num: 21, nome: "Keisuke Goto", pos: "Atacante" },
        { num: 22, nome: "Daizen Maeda", pos: "Atacante" },
        { num: 23, nome: "Koki Ogawa", pos: "Atacante" },
        { num: 24, nome: "Kento Shiogai", pos: "Atacante" },
        { num: 25, nome: "Yuito Suzuki", pos: "Atacante" },
        { num: 26, nome: "Ayase Ueda", pos: "Atacante" }
    ],
    "Marrocos": [
        // Fonte: Squad list oficial da FRMF (02/06/2026) confirmada pela FIFA.
        { num: 1, nome: "Yassine Bounou", pos: "Goleiro" },
        { num: 2, nome: "Munir El Kajoui", pos: "Goleiro" },
        { num: 3, nome: "Anas Zniti", pos: "Goleiro" },
        { num: 4, nome: "Achraf Hakimi", pos: "Defensor" },
        { num: 5, nome: "Noussair Mazraoui", pos: "Defensor" },
        { num: 6, nome: "Romain Saiss", pos: "Defensor" },
        { num: 7, nome: "Nayef Aguerd", pos: "Defensor" },
        { num: 8, nome: "Jawad El Yamiq", pos: "Defensor" },
        { num: 9, nome: "Adam Masina", pos: "Defensor" },
        { num: 10, nome: "Yahya Attiyat Allah", pos: "Defensor" },
        { num: 11, nome: "Sofyan Amrabat", pos: "Meio-campista" },
        { num: 12, nome: "Azzedine Ounahi", pos: "Meio-campista" },
        { num: 13, nome: "Bilal El Khannouss", pos: "Meio-campista" },
        { num: 14, nome: "Amine Harit", pos: "Meio-campista" },
        { num: 15, nome: "Hakim Ziyech", pos: "Atacante" },
        { num: 16, nome: "Youssef En-Nesyri", pos: "Atacante" },
        { num: 17, nome: "Sofiane Boufal", pos: "Atacante" },
        { num: 18, nome: "Ilias Chair", pos: "Atacante" },
        { num: 19, nome: "Abdessamad Ezzalzouli", pos: "Atacante" },
        { num: 20, nome: "Ez Abde", pos: "Atacante" },
        { num: 21, nome: "Amine Adli", pos: "Atacante" }
    ],
    "México": [
        // Fonte: Squad list oficial da FMF (02/06/2026). Números oficiais anunciados pela FMF em 02/06/2026.
        { num: 1, nome: "Raúl Rangel", pos: "Goleiro" },
        { num: 2, nome: "Jorge Sánchez", pos: "Defensor" },
        { num: 3, nome: "César Montes", pos: "Defensor" },
        { num: 4, nome: "Edson Álvarez", pos: "Defensor" },
        { num: 5, nome: "Johan Vásquez", pos: "Defensor" },
        { num: 6, nome: "Erik Lira", pos: "Meio-campista" },
        { num: 7, nome: "Guillermo Martínez", pos: "Atacante" },
        { num: 8, nome: "Carlos Acevedo", pos: "Goleiro" },
        { num: 9, nome: "Santiago Giménez", pos: "Atacante" },
        { num: 10, nome: "Guillermo Ochoa", pos: "Goleiro" },
        { num: 11, nome: "Jesús Gallardo", pos: "Defensor" },
        { num: 12, nome: "Mateo Chávez", pos: "Defensor" },
        { num: 13, nome: "Luis Romo", pos: "Meio-campista" },
        { num: 14, nome: "Roberto Alvarado", pos: "Meio-campista" },
        { num: 15, nome: "Israel Reyes", pos: "Defensor" },
        { num: 16, nome: "Orbelín Pineda", pos: "Meio-campista" },
        { num: 17, nome: "César Huerta", pos: "Atacante" },
        { num: 18, nome: "Julián Quiñones", pos: "Atacante" },
        { num: 19, nome: "Álvaro Fidalgo", pos: "Meio-campista" },
        { num: 20, nome: "Armando González", pos: "Atacante" },
        { num: 21, nome: "Brian Gutiérrez", pos: "Meio-campista" },
        { num: 22, nome: "Raúl Jiménez", pos: "Atacante" },
        { num: 23, nome: "Gilberto Mora", pos: "Meio-campista" },
        { num: 24, nome: "Obed Vargas", pos: "Meio-campista" },
        { num: 25, nome: "Alexis Vega", pos: "Atacante" },
        { num: 26, nome: "Luis Chávez", pos: "Meio-campista" }
    ],
    "Noruega": [
        // Fonte: Squad list oficial da NFF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Orjan Nyland", pos: "Goleiro" },
        { num: 2, nome: "Egil Selvik", pos: "Goleiro" },
        { num: 3, nome: "Mads Christiansen", pos: "Goleiro" },
        { num: 4, nome: "Kristoffer Ajer", pos: "Defensor" },
        { num: 5, nome: "Leo Ostigard", pos: "Defensor" },
        { num: 6, nome: "Andreas Hanche-Olsen", pos: "Defensor" },
        { num: 7, nome: "Marcus Holmgren Pedersen", pos: "Defensor" },
        { num: 8, nome: "Fredrik Andre Bjorkan", pos: "Defensor" },
        { num: 9, nome: "Birger Meling", pos: "Defensor" },
        { num: 10, nome: "David Moller Wolfe", pos: "Defensor" },
        { num: 11, nome: "Martin Odegaard", pos: "Meio-campista" },
        { num: 12, nome: "Sander Berge", pos: "Meio-campista" },
        { num: 13, nome: "Patrick Berg", pos: "Meio-campista" },
        { num: 14, nome: "Morten Thorsby", pos: "Meio-campista" },
        { num: 15, nome: "Kristian Thorstvedt", pos: "Meio-campista" },
        { num: 16, nome: "Hugo Vetlesen", pos: "Meio-campista" },
        { num: 17, nome: "Erling Haaland", pos: "Atacante" },
        { num: 18, nome: "Alexander Sorloth", pos: "Atacante" },
        { num: 19, nome: "Jorgen Strand Larsen", pos: "Atacante" },
        { num: 20, nome: "Oscar Bobb", pos: "Atacante" },
        { num: 21, nome: "Antonio Nusa", pos: "Atacante" }
    ],
    "Nova Zelândia": [
        // Fonte: Squad list oficial da NZF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Max Crocombe", pos: "Goleiro" },
        { num: 2, nome: "Alex Paulsen", pos: "Goleiro" },
        { num: 3, nome: "Oli Sail", pos: "Goleiro" },
        { num: 4, nome: "Nando Pijnaker", pos: "Defensor" },
        { num: 5, nome: "Bill Tuiloma", pos: "Defensor" },
        { num: 6, nome: "Tommy Smith", pos: "Defensor" },
        { num: 7, nome: "Michael Boxall", pos: "Defensor" },
        { num: 8, nome: "Francis de Vries", pos: "Defensor" },
        { num: 9, nome: "Liberato Cacace", pos: "Defensor" },
        { num: 10, nome: "Tim Payne", pos: "Defensor" },
        { num: 11, nome: "Joe Bell", pos: "Meio-campista" },
        { num: 12, nome: "Matthew Garbett", pos: "Meio-campista" },
        { num: 13, nome: "Marko Stamenic", pos: "Meio-campista" },
        { num: 14, nome: "Callum McCowatt", pos: "Meio-campista" },
        { num: 15, nome: "Elijah Just", pos: "Meio-campista" },
        { num: 16, nome: "Kosta Barbarouses", pos: "Atacante" },
        { num: 17, nome: "Chris Wood", pos: "Atacante" },
        { num: 18, nome: "Ben Waine", pos: "Atacante" },
        { num: 19, nome: "Max Mata", pos: "Atacante" }
    ],
    "Portugal": [
        // Fonte: Lista oficial da FPF divulgada em 19/05/2026. Números oficiais divulgados pela FPF e imprensa (Record) em 03/06/2026.
        { num: 1, nome: "Diogo Costa", pos: "Goleiro" },
        { num: 2, nome: "Diogo Dalot", pos: "Defensor" },
        { num: 3, nome: "Nuno Mendes", pos: "Defensor" },
        { num: 4, nome: "Ruben Dias", pos: "Defensor" },
        { num: 5, nome: "Joao Cancelo", pos: "Defensor" },
        { num: 6, nome: "Goncalo Inacio", pos: "Defensor" },
        { num: 7, nome: "Cristiano Ronaldo", pos: "Atacante" },
        { num: 8, nome: "Bruno Fernandes", pos: "Meio-campista" },
        { num: 9, nome: "Nelson Semedo", pos: "Defensor" },
        { num: 10, nome: "Bernardo Silva", pos: "Meio-campista" },
        { num: 11, nome: "Matheus Nunes", pos: "Meio-campista" },
        { num: 12, nome: "Jose Sa", pos: "Goleiro" },
        { num: 13, nome: "Joao Neves", pos: "Meio-campista" },
        { num: 14, nome: "Ruben Neves", pos: "Meio-campista" },
        { num: 15, nome: "Vitinha", pos: "Meio-campista" },
        { num: 16, nome: "Rui Silva", pos: "Goleiro" },
        { num: 17, nome: "Francisco Trincao", pos: "Atacante" },
        { num: 18, nome: "Rafael Leao", pos: "Atacante" },
        { num: 19, nome: "Joao Felix", pos: "Atacante" },
        { num: 20, nome: "Goncalo Ramos", pos: "Atacante" },
        { num: 21, nome: "Pedro Neto", pos: "Atacante" },
        { num: 22, nome: "Francisco Conceicao", pos: "Atacante" },
        { num: 23, nome: "Samu Costa", pos: "Meio-campista" }
    ],
    "Senegal": [
        // Fonte: Squad list oficial da FSF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Edouard Mendy", pos: "Goleiro" },
        { num: 2, nome: "Seny Dieng", pos: "Goleiro" },
        { num: 3, nome: "Mory Diaw", pos: "Goleiro" },
        { num: 4, nome: "Kalidou Koulibaly", pos: "Defensor" },
        { num: 5, nome: "Abdou Diallo", pos: "Defensor" },
        { num: 6, nome: "Youssouf Sabaly", pos: "Defensor" },
        { num: 7, nome: "Fode Ballo-Toure", pos: "Defensor" },
        { num: 8, nome: "Ismail Jakobs", pos: "Defensor" },
        { num: 9, nome: "Moussa Niakhate", pos: "Defensor" },
        { num: 10, nome: "Formose Mendy", pos: "Defensor" },
        { num: 11, nome: "Idrissa Gueye", pos: "Meio-campista" },
        { num: 12, nome: "Cheikhou Kouyate", pos: "Meio-campista" },
        { num: 13, nome: "Pape Gueye", pos: "Meio-campista" },
        { num: 14, nome: "Nampalys Mendy", pos: "Meio-campista" },
        { num: 15, nome: "Krepin Diatta", pos: "Meio-campista" },
        { num: 16, nome: "Sadio Mane", pos: "Atacante" },
        { num: 17, nome: "Ismaila Sarr", pos: "Atacante" },
        { num: 18, nome: "Boulaye Dia", pos: "Atacante" },
        { num: 19, nome: "Habib Diallo", pos: "Atacante" },
        { num: 20, nome: "Iliman Ndiaye", pos: "Atacante" },
        { num: 21, nome: "Nicolas Jackson", pos: "Atacante" }
    ],
    "Suécia": [
        // Fonte: Squad list oficial da SvFF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Robin Olsen", pos: "Goleiro" },
        { num: 2, nome: "Viktor Johansson", pos: "Goleiro" },
        { num: 3, nome: "Kristoffer Nordfeldt", pos: "Goleiro" },
        { num: 4, nome: "Victor Lindelof", pos: "Defensor" },
        { num: 5, nome: "Isak Hien", pos: "Defensor" },
        { num: 6, nome: "Ludwig Augustinsson", pos: "Defensor" },
        { num: 7, nome: "Emil Holm", pos: "Defensor" },
        { num: 8, nome: "Carl Starfelt", pos: "Defensor" },
        { num: 9, nome: "Jesper Holmstrom", pos: "Defensor" },
        { num: 10, nome: "Samuel Dahl", pos: "Defensor" },
        { num: 11, nome: "Dejan Kulusevski", pos: "Meio-campista" },
        { num: 12, nome: "Jens Cajuste", pos: "Meio-campista" },
        { num: 13, nome: "Jesper Karlstrom", pos: "Meio-campista" },
        { num: 14, nome: "Anton Saletros", pos: "Meio-campista" },
        { num: 15, nome: "Alexander Isak", pos: "Atacante" },
        { num: 16, nome: "Viktor Gyokeres", pos: "Atacante" },
        { num: 17, nome: "Emil Forsberg", pos: "Atacante" },
        { num: 18, nome: "Jesper Karlsson", pos: "Atacante" },
        { num: 19, nome: "Anthony Elanga", pos: "Atacante" }
    ],
    "Suíça": [
        // Fonte: Squad list oficial da SFV (02/06/2026). Numerais oficiais no site da SFV (Template Switzerland squad).
        { num: 1, nome: "Gregor Kobel", pos: "Goleiro" },
        { num: 2, nome: "Miro Muheim", pos: "Defensor" },
        { num: 3, nome: "Silvan Widmer", pos: "Defensor" },
        { num: 4, nome: "Nico Elvedi", pos: "Defensor" },
        { num: 5, nome: "Manuel Akanji", pos: "Defensor" },
        { num: 6, nome: "Denis Zakaria", pos: "Meio-campista" },
        { num: 7, nome: "Breel Embolo", pos: "Atacante" },
        { num: 8, nome: "Remo Freuler", pos: "Meio-campista" },
        { num: 9, nome: "Christian Fassnacht", pos: "Atacante" },
        { num: 10, nome: "Granit Xhaka", pos: "Meio-campista" },
        { num: 11, nome: "Dan Ndoye", pos: "Atacante" },
        { num: 12, nome: "Marvin Keller", pos: "Goleiro" },
        { num: 13, nome: "Ricardo Rodriguez", pos: "Defensor" },
        { num: 14, nome: "Fabian Rieder", pos: "Meio-campista" },
        { num: 15, nome: "Cedric Itten", pos: "Atacante" },
        { num: 16, nome: "Johan Manzambi", pos: "Meio-campista" },
        { num: 17, nome: "Zeki Amdouni", pos: "Atacante" },
        { num: 18, nome: "Yvon Mvogo", pos: "Goleiro" },
        { num: 19, nome: "Aurele Amenda", pos: "Defensor" },
        { num: 20, nome: "Luca Jaquez", pos: "Defensor" },
        { num: 21, nome: "Eray Comert", pos: "Defensor" }
    ],
    "Tunísia": [
        // Fonte: Squad list oficial da FTF (02/06/2026) conforme ESPN.
        { num: 1, nome: "Bechir Ben Said", pos: "Goleiro" },
        { num: 2, nome: "Aymen Dahmen", pos: "Goleiro" },
        { num: 3, nome: "Mouez Hassen", pos: "Goleiro" },
        { num: 4, nome: "Montassar Talbi", pos: "Defensor" },
        { num: 5, nome: "Yassine Meriah", pos: "Defensor" },
        { num: 6, nome: "Dylan Bronn", pos: "Defensor" },
        { num: 7, nome: "Ali Abdi", pos: "Defensor" },
        { num: 8, nome: "Wajdi Kechrida", pos: "Defensor" },
        { num: 9, nome: "Mohamed Drager", pos: "Defensor" },
        { num: 10, nome: "Ellyes Skhiri", pos: "Meio-campista" },
        { num: 11, nome: "Aissa Laidouni", pos: "Meio-campista" },
        { num: 12, nome: "Hannibal Mejbri", pos: "Meio-campista" },
        { num: 13, nome: "Mohamed Ali Ben Romdhane", pos: "Meio-campista" },
        { num: 14, nome: "Nader Ghandri", pos: "Meio-campista" },
        { num: 15, nome: "Youssef Msakni", pos: "Atacante" },
        { num: 16, nome: "Wahbi Khazri", pos: "Atacante" },
        { num: 17, nome: "Saifeddine Jaziri", pos: "Atacante" },
        { num: 18, nome: "Elias Achouri", pos: "Atacante" },
        { num: 19, nome: "Omar Layouni", pos: "Atacante" },
        { num: 20, nome: "Sayfallah Ltaief", pos: "Atacante" }
    ],
    "Uruguai": [
    // Fontes: Olympics.com, BBC.com (31/05/2026); numeração: Ge.globo.com (02/06/2026)
    { num: 1, nome: "Sergio Rochet", pos: "Goleiro" },
    { num: 23, nome: "Fernando Muslera", pos: "Goleiro" },
    { num: 12, nome: "Santiago Mele", pos: "Goleiro" },
    { num: 13, nome: "Guillermo Varela", pos: "Defensor" },
    { num: 4, nome: "Ronald Araujo", pos: "Defensor" },
    { num: 2, nome: "José María Giménez", pos: "Defensor" },
    { num: 24, nome: "Santiago Bueno", pos: "Defensor" },
    { num: 3, nome: "Sebastián Cáceres", pos: "Defensor" },
    { num: 16, nome: "Mathías Olivera", pos: "Defensor" },
    { num: 22, nome: "Joaquín Piquerez", pos: "Defensor" },
    { num: 17, nome: "Matías Viña", pos: "Defensor" },
    { num: 5, nome: "Manuel Ugarte", pos: "Meio-campista" },
    { num: 15, nome: "Emiliano Martínez", pos: "Meio-campista" },
    { num: 6, nome: "Rodrigo Bentancur", pos: "Meio-campista" },
    { num: 8, nome: "Federico Valverde", pos: "Meio-campista" },
    { num: 14, nome: "Agustín Canobbio", pos: "Meio-campista" },
    { num: 25, nome: "Juan Manuel Sanabria", pos: "Meio-campista" },
    { num: 10, nome: "Giorgian de Arrascaeta", pos: "Meio-campista" },
    { num: 7, nome: "Nicolás de la Cruz", pos: "Meio-campista" },
    { num: 26, nome: "Rodrigo Zalazar", pos: "Meio-campista" },
    { num: 11, nome: "Facundo Pellistri", pos: "Atacante" },
    { num: 20, nome: "Maximiliano Araújo", pos: "Atacante" },
    { num: 21, nome: "Brian Rodríguez", pos: "Atacante" },
    { num: 18, nome: "Rodrigo Aguirre", pos: "Atacante" },
    { num: 19, nome: "Darwin Núñez", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23, os cortes foram: Federico Viñas (Atacante) e mais um a confirmar.
],
"Arábia Saudita": [
    { num: 21, nome: "Nawaf Al-Aqidi", pos: "Goleiro" },
    { num: 22, nome: "Ahmed Al-Kassar", pos: "Goleiro" },
    { num: 2, nome: "Saud Abdulhamid", pos: "Defensor" },
    { num: 3, nome: "Abdulelah Al-Amri", pos: "Defensor" },
    { num: 4, nome: "Ali Lajami", pos: "Defensor" },
    { num: 5, nome: "Hassan Tambakti", pos: "Defensor" },
    { num: 6, nome: "Ali Majrashi", pos: "Defensor" },
    { num: 13, nome: "Moteb Al-Harbi", pos: "Defensor" },
    { num: 14, nome: "Jehad Thikri", pos: "Defensor" },
    { num: 15, nome: "Hassan Kadesh", pos: "Defensor" },
    { num: 16, nome: "Nawaf Boushal", pos: "Defensor" },
    { num: 17, nome: "Mohammed Abu Al-Shamat", pos: "Defensor" },
    { num: 7, nome: "Salem Al-Dawsari", pos: "Meio-campista" },
    { num: 8, nome: "Mohammed Kanno", pos: "Meio-campista" },
    { num: 9, nome: "Abdullah Al-Khaibari", pos: "Meio-campista" },
    { num: 10, nome: "Ayman Yahya", pos: "Meio-campista" },
    { num: 11, nome: "Nasser Al-Dawsari", pos: "Meio-campista" },
    { num: 12, nome: "Musab Al-Juwayr", pos: "Meio-campista" },
    { num: 18, nome: "Ziyad Al-Johani", pos: "Meio-campista" },
    { num: 19, nome: "Alaa Al-Hajji", pos: "Meio-campista" },
    { num: 20, nome: "Khalid Al-Ghannam", pos: "Meio-campista" },
    { num: 23, nome: "Sultan Mandash", pos: "Meio-campista" }
],
"Cabo Verde": [
    // Fonte: Squawka.com; numeração: Squawka.com
    { num: 1, nome: "Vozinha", pos: "Goleiro" },
    { num: 12, nome: "Marcio Rosa", pos: "Goleiro" },
    { num: 23, nome: "CJ dos Santos", pos: "Goleiro" },
    { num: 2, nome: "Stopira", pos: "Defensor" },
    { num: 4, nome: "Roberto Lopes", pos: "Defensor" },
    { num: 3, nome: "Diney", pos: "Defensor" },
    { num: 5, nome: "Logan Costa", pos: "Defensor" },
    { num: 22, nome: "Steven Moreira", pos: "Defensor" },
    { num: 24, nome: "Wagner Pina", pos: "Defensor" },
    { num: 13, nome: "Sidny Lopes Cabral", pos: "Defensor" },
    { num: 10, nome: "Jamiro Monteiro", pos: "Meio-campista" },
    { num: 6, nome: "Kevin Pina", pos: "Meio-campista" },
    { num: 14, nome: "Deroy Duarte", pos: "Meio-campista" },
    { num: 18, nome: "Telmo Arcanjo", pos: "Meio-campista" },
    { num: 15, nome: "Laros Duarte", pos: "Meio-campista" },
    { num: 20, nome: "Ryan Mendes", pos: "Atacante" },
    { num: 11, nome: "Garry Rodrigues", pos: "Atacante" },
    { num: 7, nome: "Jovane Cabral", pos: "Atacante" },
    { num: 9, nome: "Gilson Benchimol", pos: "Atacante" },
    { num: 19, nome: "Dailon Livramento", pos: "Atacante" },
    { num: 26, nome: "Helio Varela", pos: "Atacante" },
    { num: 21, nome: "Nuno da Costa", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23. Os cortes foram: Joao Paulo (DF), Yannick Semedo (MF), Willy Semedo (FW). Um jogador adicional (Kelvin Pires) pode ser cortado.
],
"Jordânia": [
    // Fonte: Olympics.com, Khelnow.com; numeração: Khelnow.com
    { num: 1, nome: "Yazeed Abu Laila", pos: "Goleiro" },
    { num: 22, nome: "Abdullah Al-Fakhouri", pos: "Goleiro" },
    { num: 12, nome: "Noor Bani Attiah", pos: "Goleiro" },
    { num: 3, nome: "Abdallah Nasib", pos: "Defensor" },
    { num: 19, nome: "Saed Al-Rosan", pos: "Defensor" },
    { num: 5, nome: "Yazan Al-Arab", pos: "Defensor" },
    { num: 17, nome: "Saleem Obaid", pos: "Defensor" },
    { num: 16, nome: "Mohammad Abu Al-Nadi", pos: "Defensor" },
    { num: 4, nome: "Husam Abu Dahab", pos: "Defensor" },
    { num: 23, nome: "Ehsan Haddad", pos: "Defensor" },
    { num: 2, nome: "Mohammad Abu Hashish", pos: "Defensor" },
    { num: 20, nome: "Mohammad Abu Taha", pos: "Defensor" },
    { num: 21, nome: "Nizar Al-Rashdan", pos: "Meio-campista" },
    { num: 14, nome: "Rajaei Ayed", pos: "Meio-campista" },
    { num: 6, nome: "Amer Jamous", pos: "Meio-campista" },
    { num: 15, nome: "Ibrahim Sadeh", pos: "Meio-campista" },
    { num: 25, nome: "Mohammad Al-Dawoud", pos: "Meio-campista" },
    { num: 13, nome: "Mahmoud Al-Mardi", pos: "Meio-campista" },
    { num: 10, nome: "Mousa Al-Tamari", pos: "Atacante" },
    { num: 8, nome: "Odeh Al-Fakhouri", pos: "Atacante" },
    { num: 7, nome: "Mohammad Abu Zrayq", pos: "Atacante" },
    { num: 24, nome: "Ali Azaizeh", pos: "Atacante" },
    { num: 18, nome: "Ali Olwan", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23. Os cortes foram: Ouda Fakhouri (FW), Ibrahim Sabra (FW), Anas Badawi (DF). Um jogador adicional (Noor Al-Rawabdeh - MF) pode ser cortado.
],
"Argélia": [
    // Fonte: Olympics.com, BBC.com; numeração: foot-africa.com
    { num: 23, nome: "Luca Zidane", pos: "Goleiro" },
    { num: 16, nome: "Oussama Benbot", pos: "Goleiro" },
    { num: 1, nome: "Melvin Mastil", pos: "Goleiro" },
    { num: 17, nome: "Rafik Belghali", pos: "Defensor" },
    { num: 26, nome: "Samir Chergui", pos: "Defensor" },
    { num: 15, nome: "Rayan Aït-Nouri", pos: "Defensor" },
    { num: 13, nome: "Jaouen Hadjam", pos: "Defensor" },
    { num: 2, nome: "Aïssa Mandi", pos: "Defensor" },
    { num: 21, nome: "Ramy Bensebaïni", pos: "Defensor" },
    { num: 5, nome: "Zineddine Belaïd", pos: "Defensor" },
    { num: 4, nome: "Mohamed Amine Tougaï", pos: "Defensor" },
    { num: 3, nome: "Achraf Abada", pos: "Defensor" },
    { num: 19, nome: "Nabil Bentaleb", pos: "Meio-campista" },
    { num: 14, nome: "Hicham Boudaoui", pos: "Meio-campista" },
    { num: 8, nome: "Houssem Aouar", pos: "Meio-campista" },
    { num: 10, nome: "Farès Chaïbi", pos: "Meio-campista" },
    { num: 22, nome: "Ibrahim Maza", pos: "Meio-campista" },
    { num: 24, nome: "Yacine Titraoui", pos: "Meio-campista" },
    { num: 6, nome: "Ramiz Zerrouki", pos: "Meio-campista" },
    { num: 18, nome: "Mohamed Amine Amoura", pos: "Atacante" },
    { num: 12, nome: "Nadhir Benbouali", pos: "Atacante" },
    { num: 20, nome: "Adil Boulbina", pos: "Atacante" },
    { num: 25, nome: "Farès Ghedjemis", pos: "Atacante" },
    { num: 9, nome: "Amine Gouiri", pos: "Atacante" },
    { num: 11, nome: "Anis Hadj Moussa", pos: "Atacante" },
    { num: 7, nome: "Riyad Mahrez", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23.
],
"Uzbequistão": [
    // Fonte: Olympics.com, BBC.com
    { num: 1, nome: "Utkir Yusupov", pos: "Goleiro" },
    { num: 12, nome: "Abduvohid Nematov", pos: "Goleiro" },
    { num: 21, nome: "Botirali Ergashev", pos: "Goleiro" },
    { num: 2, nome: "Khojiakbar Alijonov", pos: "Defensor" },
    { num: 3, nome: "Abdukodir Khusanov", pos: "Defensor" },
    { num: 4, nome: "Rustam Ashurmatov", pos: "Defensor" },
    { num: 5, nome: "Farrukh Sayfiev", pos: "Defensor" },
    { num: 6, nome: "Otabek Shukurov", pos: "Meio-campista" },
    { num: 7, nome: "Jaloliddin Masharipov", pos: "Meio-campista" },
    { num: 8, nome: "Odiljon Hamrobekov", pos: "Meio-campista" },
    { num: 9, nome: "Oston Urunov", pos: "Meio-campista" },
    { num: 10, nome: "Jamshid Iskanderov", pos: "Meio-campista" },
    { num: 11, nome: "Dostonbek Khamdamov", pos: "Meio-campista" },
    { num: 13, nome: "Sherzod Nasrullaev", pos: "Defensor" },
    { num: 14, nome: "Abbosbek Fayzullaev", pos: "Meio-campista" },
    { num: 15, nome: "Umar Eshmurodov", pos: "Defensor" },
    { num: 16, nome: "Eldor Shomurodov", pos: "Atacante" },
    { num: 17, nome: "Akmal Mozgovoy", pos: "Meio-campista" },
    { num: 18, nome: "Azizjon Ganiev", pos: "Meio-campista" },
    { num: 19, nome: "Abdulla Abdullaev", pos: "Defensor" },
    { num: 20, nome: "Sherzod Esanov", pos: "Meio-campista" },
    { num: 22, nome: "Igor Sergeev", pos: "Atacante" },
    { num: 23, nome: "Azizbek Amonov", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23. Os cortes foram: Bekhruz Karimov (DF), Jakhongir Urozov (DF), Avazbek Ulmasaliev (DF).
],
"RD Congo": [
    // Fonte: Olympics.com, BBC.com
    { num: 1, nome: "Lionel Mpasi", pos: "Goleiro" },
    { num: 12, nome: "Timothy Fayulu", pos: "Goleiro" },
    { num: 21, nome: "Matthieu Epolo", pos: "Goleiro" },
    { num: 2, nome: "Aaron Wan-Bissaka", pos: "Defensor" },
    { num: 3, nome: "Steve Kapuadi", pos: "Defensor" },
    { num: 4, nome: "Axel Tuanzebe", pos: "Defensor" },
    { num: 5, nome: "Dylan Batubinsika", pos: "Defensor" },
    { num: 13, nome: "Chancel Mbemba", pos: "Defensor" },
    { num: 14, nome: "Arthur Masuaku", pos: "Defensor" },
    { num: 15, nome: "Joris Kayembe", pos: "Defensor" },
    { num: 6, nome: "Noah Sadiki", pos: "Meio-campista" },
    { num: 7, nome: "Samuel Moutoussamy", pos: "Meio-campista" },
    { num: 8, nome: "Edo Kayembe", pos: "Meio-campista" },
    { num: 16, nome: "Theo Bongonda", pos: "Meio-campista" },
    { num: 17, nome: "Charles Pickel", pos: "Meio-campista" },
    { num: 9, nome: "Cedric Bakambu", pos: "Atacante" },
    { num: 10, nome: "Simon Banza", pos: "Atacante" },
    { num: 11, nome: "Fiston Mayele", pos: "Atacante" },
    { num: 18, nome: "Yoane Wissa", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23.
],
"Gana": [
    // Fonte: Olympics.com, Ghanafa.org; numeração: Ghanafa.org
    { num: 1, nome: "Lawrence Ati-Zigi", pos: "Goleiro" },
    { num: 12, nome: "Benjamin Asare", pos: "Goleiro" },
    { num: 16, nome: "Joseph Anang", pos: "Goleiro" },
    { num: 2, nome: "Alidu Seidu", pos: "Defensor" },
    { num: 4, nome: "Mohammed Salisu", pos: "Defensor" },
    { num: 5, nome: "Thomas Partey", pos: "Meio-campista" },
    { num: 6, nome: "Kwasi Sibo", pos: "Meio-campista" },
    { num: 7, nome: "Elisha Owusu", pos: "Meio-campista" },
    { num: 8, nome: "James Ofori", pos: "Defensor" },
    { num: 9, nome: "Jordan Ayew", pos: "Atacante" },
    { num: 10, nome: "Brandon Thomas-Asante", pos: "Atacante" },
    { num: 11, nome: "Antoine Semenyo", pos: "Atacante" },
    { num: 13, nome: "Gideon Mensah", pos: "Defensor" },
    { num: 14, nome: "Caleb Yirenkyi", pos: "Meio-campista" },
    { num: 15, nome: "Edmund Arko-Mensah", pos: "Defensor" },
    { num: 17, nome: "Baba Rahman", pos: "Defensor" },
    { num: 18, nome: "Daniel Kofi-Kyereh", pos: "Atacante" },
    { num: 19, nome: "Inaki Williams", pos: "Atacante" },
    { num: 20, nome: "Mohammed Kudus", pos: "Meio-campista" },
    { num: 21, nome: "Alexander Djiku", pos: "Defensor" },
    { num: 22, nome: "Kamaldeen Sulemana", pos: "Atacante" },
    { num: 23, nome: "Derrick Luckassen", pos: "Defensor" },
    { num: 24, nome: "Ernest Nuamah", pos: "Atacante" }
    // Nota: Foram convocados 28 jogadores. Lista reduzida para 23.
],
"República Tcheca": [
    { num: 1, nome: "Matěj Kovář", pos: "Goleiro" },
    { num: 16, nome: "Jindřich Staněk", pos: "Goleiro" },
    { num: 23, nome: "Lukáš Horníček", pos: "Goleiro" },
    { num: 5, nome: "Vladimír Coufal", pos: "Defensor" },
    { num: 3, nome: "Tomáš Holeš", pos: "Defensor" },
    { num: 7, nome: "Ladislav Krejčí", pos: "Defensor" },
    { num: 2, nome: "David Zima", pos: "Defensor" },
    { num: 20, nome: "Jaroslav Zelený", pos: "Defensor" },
    { num: 14, nome: "David Jurásek", pos: "Defensor" },
    { num: 21, nome: "David Douděra", pos: "Defensor" },
    { num: 4, nome: "Robin Hranáč", pos: "Defensor" },
    { num: 6, nome: "Štěpán Chaloupek", pos: "Defensor" },
    { num: 22, nome: "Tomáš Souček", pos: "Meio-campista" },
    { num: 8, nome: "Vladimír Darida", pos: "Meio-campista" },
    { num: 17, nome: "Lukáš Provod", pos: "Meio-campista" },
    { num: 18, nome: "Michal Sadílek", pos: "Meio-campista" },
    { num: 15, nome: "Pavel Šulc", pos: "Meio-campista" },
    { num: 12, nome: "Lukáš Červ", pos: "Meio-campista" },
    { num: 25, nome: "Hugo Sochůrek", pos: "Meio-campista" },
    { num: 24, nome: "Alexandr Sojka", pos: "Meio-campista" },
    { num: 26, nome: "Denis Višinský", pos: "Meio-campista" },
    { num: 10, nome: "Patrik Schick", pos: "Atacante" },
    { num: 9, nome: "Adam Hložek", pos: "Atacante" },
    { num: 11, nome: "Jan Kuchta", pos: "Atacante" },
    { num: 13, nome: "Mojmír Chytil", pos: "Atacante" },
    { num: 19, nome: "Tomáš Chorý", pos: "Atacante" }
],
"Panamá": [
    // Fonte: Sportingnews.com, AS.com
    { num: 1, nome: "Luis Mejía", pos: "Goleiro" },
    { num: 2, nome: "César Samudio", pos: "Goleiro" },
    { num: 3, nome: "Orlando Mosquera", pos: "Goleiro" },
    { num: 4, nome: "César Blackman", pos: "Defensor" },
    { num: 5, nome: "Jorge Gutiérrez", pos: "Defensor" },
    { num: 6, nome: "Amir Murillo", pos: "Defensor" },
    { num: 7, nome: "Fidel Escobar", pos: "Defensor" },
    { num: 8, nome: "Andrés Andrade", pos: "Defensor" },
    { num: 9, nome: "Edgargo Fariña", pos: "Defensor" },
    { num: 10, nome: "José Córdoba", pos: "Defensor" },
    { num: 11, nome: "Eric Davis", pos: "Defensor" },
    { num: 12, nome: "Jiovany Ramos", pos: "Defensor" },
    { num: 13, nome: "Roderick Miller", pos: "Defensor" },
    { num: 14, nome: "Aníbal Godoy", pos: "Meio-campista" },
    { num: 15, nome: "Adalberto Carrasquilla", pos: "Meio-campista" },
    { num: 16, nome: "Carlos Harvey", pos: "Meio-campista" },
    { num: 17, nome: "Cristian Martínez", pos: "Meio-campista" },
    { num: 18, nome: "Ángel Orelien", pos: "Meio-campista" },
    { num: 19, nome: "Yoel Bárcenas", pos: "Atacante" },
    { num: 20, nome: "Alberto Quintero", pos: "Atacante" },
    { num: 21, nome: "Ismael Díaz", pos: "Atacante" },
    { num: 22, nome: "Tomás Rodríguez", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23.
],
"Equador": [
    // Fonte: Olympics.com, FEF
    { num: 1, nome: "Hernán Galíndez", pos: "Goleiro" },
    { num: 2, nome: "Moisés Ramírez", pos: "Goleiro" },
    { num: 3, nome: "Gonzalo Valle", pos: "Goleiro" },
    { num: 4, nome: "Piero Hincapié", pos: "Defensor" },
    { num: 5, nome: "Joel Ordóñez", pos: "Defensor" },
    { num: 6, nome: "Willian Pacho", pos: "Defensor" },
    { num: 7, nome: "Jackson Porozo", pos: "Defensor" },
    { num: 8, nome: "Félix Torres", pos: "Defensor" },
    { num: 9, nome: "Pervis Estupiñán", pos: "Defensor" },
    { num: 10, nome: "Jordy Alcívar", pos: "Meio-campista" },
    { num: 11, nome: "Angelo Preciado", pos: "Defensor" },
    { num: 12, nome: "Moisés Caicedo", pos: "Meio-campista" },
    { num: 13, nome: "Alan Franco", pos: "Meio-campista" },
    { num: 14, nome: "Kendry Páez", pos: "Meio-campista" },
    { num: 15, nome: "Pedro Vite", pos: "Meio-campista" },
    { num: 16, nome: "Gonzalo Plata", pos: "Atacante" },
    { num: 17, nome: "John Yeboah", pos: "Atacante" },
    { num: 18, nome: "Enner Valencia", pos: "Atacante" },
    { num: 19, nome: "Kevin Rodríguez", pos: "Atacante" },
    { num: 20, nome: "Jordy Caicedo", pos: "Atacante" },
    { num: 21, nome: "Jeremy Arévalo", pos: "Atacante" },
    { num: 22, nome: "Nilson Angulo", pos: "Atacante" },
    { num: 23, nome: "Anthony Valencia", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23.
],
"Haiti": [
    // Fonte: Olympics.com, Beinsports.com
    { num: 1, nome: "Johny Placide", pos: "Goleiro" },
    { num: 12, nome: "Alexandre Pierre", pos: "Goleiro" },
    { num: 23, nome: "Josué Duverger", pos: "Goleiro" },
    { num: 2, nome: "Carlens Arcus", pos: "Defensor" },
    { num: 3, nome: "Wilguens Paugain", pos: "Defensor" },
    { num: 4, nome: "Duke Lacroix", pos: "Defensor" },
    { num: 5, nome: "Martin Expérience", pos: "Defensor" },
    { num: 6, nome: "Jean-Kévin Duverne", pos: "Defensor" },
    { num: 13, nome: "Ricardo Adé", pos: "Defensor" },
    { num: 14, nome: "Hannes Delcroix", pos: "Defensor" },
    { num: 7, nome: "Carl-Fred Sainthe", pos: "Meio-campista" },
    { num: 8, nome: "Jean-Jacques Danley", pos: "Meio-campista" },
    { num: 15, nome: "Garven-Michée Metusala", pos: "Meio-campista" },
    { num: 16, nome: "Jean-Ricner Bellegarde", pos: "Meio-campista" },
    { num: 17, nome: "Woodensky Pierre", pos: "Meio-campista" },
    { num: 18, nome: "Dominique Simon", pos: "Meio-campista" },
    { num: 9, nome: "Louicius Déedson", pos: "Atacante" },
    { num: 10, nome: "Ruben Providence", pos: "Atacante" },
    { num: 11, nome: "Josué Casimir", pos: "Atacante" },
    { num: 19, nome: "Derrick Etienne", pos: "Atacante" },
    { num: 20, nome: "Wilson Isidor", pos: "Atacante" },
    { num: 21, nome: "Duckens Nazon", pos: "Atacante" },
    { num: 22, nome: "Frantzdy Pierrot", pos: "Atacante" },
    { num: 24, nome: "Lenny Joseph", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23. Os cortes foram: Yassin Fortune (FW), jogador adicional a confirmar.
],
"Turquia": [
    // Fonte: Beinsports.com, Olympics.com
    { num: 1, nome: "Mert Günok", pos: "Goleiro" },
    { num: 12, nome: "Altay Bayındır", pos: "Goleiro" },
    { num: 23, nome: "Uğurcan Çakır", pos: "Goleiro" },
    { num: 2, nome: "Zeki Çelik", pos: "Defensor" },
    { num: 3, nome: "Merih Demiral", pos: "Defensor" },
    { num: 4, nome: "Çağlar Söyüncü", pos: "Defensor" },
    { num: 5, nome: "Ozan Kabak", pos: "Defensor" },
    { num: 6, nome: "Ferdi Kadıoğlu", pos: "Defensor" },
    { num: 7, nome: "Kerem Aktürkoğlu", pos: "Atacante" },
    { num: 8, nome: "Arda Güler", pos: "Atacante" },
    { num: 9, nome: "Hakan Çalhanoğlu", pos: "Meio-campista" },
    { num: 10, nome: "Orkun Kökçü", pos: "Meio-campista" },
    { num: 11, nome: "Barış Alper Yılmaz", pos: "Atacante" },
    { num: 14, nome: "İsmail Yüksek", pos: "Meio-campista" },
    { num: 15, nome: "Salih Özcan", pos: "Meio-campista" },
    { num: 16, nome: "Kaan Ayhan", pos: "Defensor" },
    { num: 17, nome: "Yunus Akgün", pos: "Atacante" },
    { num: 18, nome: "Oğuz Aydın", pos: "Atacante" },
    { num: 19, nome: "Kenan Yıldız", pos: "Atacante" },
    { num: 20, nome: "Deniz Gül", pos: "Atacante" },
    { num: 21, nome: "Can Uzun", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23.
],
"Paraguai": [
    // Fonte: Sportingnews.com, APF
    { num: 1, nome: "Gatito Fernández", pos: "Goleiro" },
    { num: 12, nome: "Orlando Gill", pos: "Goleiro" },
    { num: 22, nome: "Gastón Olveira", pos: "Goleiro" },
    { num: 2, nome: "Gustavo Velázquez", pos: "Defensor" },
    { num: 3, nome: "Omar Alderete", pos: "Defensor" },
    { num: 4, nome: "Juan José Cáceres", pos: "Defensor" },
    { num: 5, nome: "Fabián Balbuena", pos: "Defensor" },
    { num: 6, nome: "Junior Alonso", pos: "Defensor" },
    { num: 7, nome: "Gustavo Gómez", pos: "Defensor" },
    { num: 8, nome: "Damián Bobadilla", pos: "Meio-campista" },
    { num: 9, nome: "Andrés Cubas", pos: "Meio-campista" },
    { num: 10, nome: "Diego Gómez", pos: "Meio-campista" },
    { num: 11, nome: "Braian Ojeda", pos: "Meio-campista" },
    { num: 13, nome: "Alejandro Romero Gamarra", pos: "Meio-campista" },
    { num: 14, nome: "Mauricio", pos: "Meio-campista" },
    { num: 15, nome: "Álex Arce", pos: "Atacante" },
    { num: 16, nome: "Antonio Sanabria", pos: "Atacante" },
    { num: 17, nome: "Isidro Pitta", pos: "Atacante" },
    { num: 18, nome: "Miguel Almirón", pos: "Atacante" },
    { num: 19, nome: "Gabriel Ávalos", pos: "Atacante" },
    { num: 20, nome: "Julio Enciso", pos: "Atacante" },
    { num: 21, nome: "Gustavo Caballero", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23.
],
"Curaçao": [
    // Fonte: Olympics.com, AS.com
    { num: 1, nome: "Tyrick Bodak", pos: "Goleiro" },
    { num: 2, nome: "Trevor Doornbusch", pos: "Goleiro" },
    { num: 3, nome: "Eloy Room", pos: "Goleiro" },
    { num: 4, nome: "Riechedly Bazoer", pos: "Defensor" },
    { num: 5, nome: "Joshua Brenet", pos: "Defensor" },
    { num: 6, nome: "Roshon van Eijma", pos: "Defensor" },
    { num: 7, nome: "Sherel Floranus", pos: "Defensor" },
    { num: 8, nome: "Deveron Fonville", pos: "Defensor" },
    { num: 9, nome: "Jurien Gaari", pos: "Defensor" },
    { num: 10, nome: "Armando Obispo", pos: "Defensor" },
    { num: 11, nome: "Shurandy Sambo", pos: "Defensor" },
    { num: 12, nome: "Juninho Bacuna", pos: "Meio-campista" },
    { num: 13, nome: "Leandro Bacuna", pos: "Meio-campista" },
    { num: 14, nome: "Livano Comenencia", pos: "Meio-campista" },
    { num: 15, nome: "Kevin Felida", pos: "Meio-campista" },
    { num: 16, nome: "Ar'jany Martha", pos: "Meio-campista" },
    { num: 17, nome: "Tyrese Noslin", pos: "Meio-campista" },
    { num: 18, nome: "Godfried Roemeratoe", pos: "Meio-campista" },
    { num: 19, nome: "Jeremy Antonisse", pos: "Atacante" },
    { num: 20, nome: "Tahith Chong", pos: "Atacante" },
    { num: 21, nome: "Kenji Gorre", pos: "Atacante" },
    { num: 22, nome: "Sontje Hansen", pos: "Atacante" },
    { num: 23, nome: "Gervane Kastaneer", pos: "Atacante" },
    { num: 24, nome: "Brandley Kuwas", pos: "Atacante" },
    { num: 25, nome: "Jurgen Locadia", pos: "Atacante" },
    { num: 26, nome: "Jearl Margaritha", pos: "Atacante" }
    // Nota: Foram convocados 26 jogadores. Lista reduzida para 23.
]
};

// Exportação para uso em outros arquivos (se necessário)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = elencosOficiais;
}